// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rocktreeTasks.proto

package rocktreeTasks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务类型枚举
type Type int32

const (
	Type_BULK_METADATA Type = 0 // 批量元数据
	Type_NODE_DATA     Type = 1 // 节点数据
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "BULK_METADATA",
		1: "NODE_DATA",
	}
	Type_value = map[string]int32{
		"BULK_METADATA": 0,
		"NODE_DATA":     1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_rocktreeTasks_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_rocktreeTasks_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_rocktreeTasks_proto_rawDescGZIP(), []int{0}
}

// 任务请求
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`              // 客户端 ID
	Type          Type                   `protobuf:"varint,2,opt,name=type,proto3,enum=rocktreeTasks.Type" json:"type,omitempty"`             // 任务类型
	Tilekey       string                 `protobuf:"bytes,3,opt,name=tilekey,proto3" json:"tilekey,omitempty"`                                // 瓦片键
	Epoch         int32                  `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`                                   // 纪元
	ImageryEpoch  int32                  `protobuf:"varint,5,opt,name=imagery_epoch,json=imageryEpoch,proto3" json:"imagery_epoch,omitempty"` // 图像纪元（可选，允许为空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_rocktreeTasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rocktreeTasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_rocktreeTasks_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TaskRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_BULK_METADATA
}

func (x *TaskRequest) GetTilekey() string {
	if x != nil {
		return x.Tilekey
	}
	return ""
}

func (x *TaskRequest) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TaskRequest) GetImageryEpoch() int32 {
	if x != nil {
		return x.ImageryEpoch
	}
	return 0
}

// 任务响应
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`              // 客户端 ID（回显）
	Type          Type                   `protobuf:"varint,2,opt,name=type,proto3,enum=rocktreeTasks.Type" json:"type,omitempty"`             // 任务类型（回显）
	Tilekey       string                 `protobuf:"bytes,3,opt,name=tilekey,proto3" json:"tilekey,omitempty"`                                // 瓦片键（回显）
	Epoch         int32                  `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`                                   // 纪元（回显）
	ImageryEpoch  int32                  `protobuf:"varint,5,opt,name=imagery_epoch,json=imageryEpoch,proto3" json:"imagery_epoch,omitempty"` // 图像纪元（回显，允许为空）
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`                                      // 响应体（仅状态码 200 时返回，其他状态码为空）
	StatusCode    int32                  `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`       // HTTP 状态码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_rocktreeTasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rocktreeTasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_rocktreeTasks_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TaskResponse) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_BULK_METADATA
}

func (x *TaskResponse) GetTilekey() string {
	if x != nil {
		return x.Tilekey
	}
	return ""
}

func (x *TaskResponse) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TaskResponse) GetImageryEpoch() int32 {
	if x != nil {
		return x.ImageryEpoch
	}
	return 0
}

func (x *TaskResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TaskResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_rocktreeTasks_proto protoreflect.FileDescriptor

const file_rocktreeTasks_proto_rawDesc = "" +
	"\n" +
	"\x13rocktreeTasks.proto\x12\rrocktreeTasks\"\xa8\x01\n" +
	"\vTaskRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.rocktreeTasks.TypeR\x04type\x12\x18\n" +
	"\atilekey\x18\x03 \x01(\tR\atilekey\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x05R\x05epoch\x12#\n" +
	"\rimagery_epoch\x18\x05 \x01(\x05R\fimageryEpoch\"\xde\x01\n" +
	"\fTaskResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.rocktreeTasks.TypeR\x04type\x12\x18\n" +
	"\atilekey\x18\x03 \x01(\tR\atilekey\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x05R\x05epoch\x12#\n" +
	"\rimagery_epoch\x18\x05 \x01(\x05R\fimageryEpoch\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12\x1f\n" +
	"\vstatus_code\x18\a \x01(\x05R\n" +
	"statusCode*(\n" +
	"\x04Type\x12\x11\n" +
	"\rBULK_METADATA\x10\x00\x12\r\n" +
	"\tNODE_DATA\x10\x012]\n" +
	"\x13RockTreeTaskService\x12F\n" +
	"\vProcessTask\x12\x1a.rocktreeTasks.TaskRequest\x1a\x1b.rocktreeTasks.TaskResponseB!Z\x1futls_client/proto/rocktreeTasksb\x06proto3"

var (
	file_rocktreeTasks_proto_rawDescOnce sync.Once
	file_rocktreeTasks_proto_rawDescData []byte
)

func file_rocktreeTasks_proto_rawDescGZIP() []byte {
	file_rocktreeTasks_proto_rawDescOnce.Do(func() {
		file_rocktreeTasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rocktreeTasks_proto_rawDesc), len(file_rocktreeTasks_proto_rawDesc)))
	})
	return file_rocktreeTasks_proto_rawDescData
}

var file_rocktreeTasks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rocktreeTasks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rocktreeTasks_proto_goTypes = []any{
	(Type)(0),            // 0: rocktreeTasks.Type
	(*TaskRequest)(nil),  // 1: rocktreeTasks.TaskRequest
	(*TaskResponse)(nil), // 2: rocktreeTasks.TaskResponse
}
var file_rocktreeTasks_proto_depIdxs = []int32{
	0, // 0: rocktreeTasks.TaskRequest.type:type_name -> rocktreeTasks.Type
	0, // 1: rocktreeTasks.TaskResponse.type:type_name -> rocktreeTasks.Type
	1, // 2: rocktreeTasks.RockTreeTaskService.ProcessTask:input_type -> rocktreeTasks.TaskRequest
	2, // 3: rocktreeTasks.RockTreeTaskService.ProcessTask:output_type -> rocktreeTasks.TaskResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rocktreeTasks_proto_init() }
func file_rocktreeTasks_proto_init() {
	if File_rocktreeTasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rocktreeTasks_proto_rawDesc), len(file_rocktreeTasks_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rocktreeTasks_proto_goTypes,
		DependencyIndexes: file_rocktreeTasks_proto_depIdxs,
		EnumInfos:         file_rocktreeTasks_proto_enumTypes,
		MessageInfos:      file_rocktreeTasks_proto_msgTypes,
	}.Build()
	File_rocktreeTasks_proto = out.File
	file_rocktreeTasks_proto_goTypes = nil
	file_rocktreeTasks_proto_depIdxs = nil
}
