// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/rocktree/RockTree.proto

package rocktree

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BulkMetadataResponseMode 枚举定义批量元数据响应模式
type ViewportMetadataRequest_BulkMetadataResponseMode int32

const (
	ViewportMetadataRequest_NONE                 ViewportMetadataRequest_BulkMetadataResponseMode = 0 // 无响应模式
	ViewportMetadataRequest_SPDY_PUSH            ViewportMetadataRequest_BulkMetadataResponseMode = 1 // SPDY 推送模式
	ViewportMetadataRequest_IN_VIEWPORT_METADATA ViewportMetadataRequest_BulkMetadataResponseMode = 2 // 在视口元数据中
)

// Enum value maps for ViewportMetadataRequest_BulkMetadataResponseMode.
var (
	ViewportMetadataRequest_BulkMetadataResponseMode_name = map[int32]string{
		0: "NONE",
		1: "SPDY_PUSH",
		2: "IN_VIEWPORT_METADATA",
	}
	ViewportMetadataRequest_BulkMetadataResponseMode_value = map[string]int32{
		"NONE":                 0,
		"SPDY_PUSH":            1,
		"IN_VIEWPORT_METADATA": 2,
	}
)

func (x ViewportMetadataRequest_BulkMetadataResponseMode) Enum() *ViewportMetadataRequest_BulkMetadataResponseMode {
	p := new(ViewportMetadataRequest_BulkMetadataResponseMode)
	*p = x
	return p
}

func (x ViewportMetadataRequest_BulkMetadataResponseMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewportMetadataRequest_BulkMetadataResponseMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rocktree_RockTree_proto_enumTypes[0].Descriptor()
}

func (ViewportMetadataRequest_BulkMetadataResponseMode) Type() protoreflect.EnumType {
	return &file_proto_rocktree_RockTree_proto_enumTypes[0]
}

func (x ViewportMetadataRequest_BulkMetadataResponseMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ViewportMetadataRequest_BulkMetadataResponseMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ViewportMetadataRequest_BulkMetadataResponseMode(num)
	return nil
}

// Deprecated: Use ViewportMetadataRequest_BulkMetadataResponseMode.Descriptor instead.
func (ViewportMetadataRequest_BulkMetadataResponseMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{2, 0}
}

// Flags 元数据标志位定义
// 组合使用位掩码表示节点特性：
// RICH3D_LEAF - 富几何细节的叶子节点
// RICH3D_NODATA - 无效节点（保留结构但无数据）
// LEAF - 基础叶子节点标识
// NODATA - 无有效数据节点
// USE_IMAGERY_EPOCH - 使用独立影像时间戳
type NodeMetadata_Flags int32

const (
	NodeMetadata_RICH3D_LEAF       NodeMetadata_Flags = 1  // 富几何细节的叶子节点
	NodeMetadata_RICH3D_NODATA     NodeMetadata_Flags = 2  // 无效节点（保留结构但无数据）
	NodeMetadata_LEAF              NodeMetadata_Flags = 4  // 基础叶子节点标识
	NodeMetadata_NODATA            NodeMetadata_Flags = 8  // 无有效数据节点
	NodeMetadata_USE_IMAGERY_EPOCH NodeMetadata_Flags = 16 // 使用独立影像时间戳
)

// Enum value maps for NodeMetadata_Flags.
var (
	NodeMetadata_Flags_name = map[int32]string{
		1:  "RICH3D_LEAF",
		2:  "RICH3D_NODATA",
		4:  "LEAF",
		8:  "NODATA",
		16: "USE_IMAGERY_EPOCH",
	}
	NodeMetadata_Flags_value = map[string]int32{
		"RICH3D_LEAF":       1,
		"RICH3D_NODATA":     2,
		"LEAF":              4,
		"NODATA":            8,
		"USE_IMAGERY_EPOCH": 16,
	}
)

func (x NodeMetadata_Flags) Enum() *NodeMetadata_Flags {
	p := new(NodeMetadata_Flags)
	*p = x
	return p
}

func (x NodeMetadata_Flags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeMetadata_Flags) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rocktree_RockTree_proto_enumTypes[1].Descriptor()
}

func (NodeMetadata_Flags) Type() protoreflect.EnumType {
	return &file_proto_rocktree_RockTree_proto_enumTypes[1]
}

func (x NodeMetadata_Flags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *NodeMetadata_Flags) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = NodeMetadata_Flags(num)
	return nil
}

// Deprecated: Use NodeMetadata_Flags.Descriptor instead.
func (NodeMetadata_Flags) EnumDescriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{12, 0}
}

// Layer 枚举定义图层类型
type Mesh_Layer int32

const (
	Mesh_OVERGROUND             Mesh_Layer = 0 // 地上图层
	Mesh_TERRAIN_BELOW_WATER    Mesh_Layer = 1 // 水下地形
	Mesh_TERRAIN_ABOVE_WATER    Mesh_Layer = 2 // 水上地形
	Mesh_TERRAIN_HIDDEN         Mesh_Layer = 3 // 隐藏地形
	Mesh_WATER                  Mesh_Layer = 4 // 水面
	Mesh_WATER_SKIRTS           Mesh_Layer = 5 // 水面裙边
	Mesh_WATER_SKIRTS_INVERTED  Mesh_Layer = 6 // 反向水面裙边
	Mesh_OVERLAY_SURFACE        Mesh_Layer = 7 // 覆盖面
	Mesh_OVERLAY_SURFACE_SKIRTS Mesh_Layer = 8 // 覆盖面裙边
	Mesh_NUM_LAYERS             Mesh_Layer = 9 // 图层数量
)

// Enum value maps for Mesh_Layer.
var (
	Mesh_Layer_name = map[int32]string{
		0: "OVERGROUND",
		1: "TERRAIN_BELOW_WATER",
		2: "TERRAIN_ABOVE_WATER",
		3: "TERRAIN_HIDDEN",
		4: "WATER",
		5: "WATER_SKIRTS",
		6: "WATER_SKIRTS_INVERTED",
		7: "OVERLAY_SURFACE",
		8: "OVERLAY_SURFACE_SKIRTS",
		9: "NUM_LAYERS",
	}
	Mesh_Layer_value = map[string]int32{
		"OVERGROUND":             0,
		"TERRAIN_BELOW_WATER":    1,
		"TERRAIN_ABOVE_WATER":    2,
		"TERRAIN_HIDDEN":         3,
		"WATER":                  4,
		"WATER_SKIRTS":           5,
		"WATER_SKIRTS_INVERTED":  6,
		"OVERLAY_SURFACE":        7,
		"OVERLAY_SURFACE_SKIRTS": 8,
		"NUM_LAYERS":             9,
	}
)

func (x Mesh_Layer) Enum() *Mesh_Layer {
	p := new(Mesh_Layer)
	*p = x
	return p
}

func (x Mesh_Layer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mesh_Layer) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rocktree_RockTree_proto_enumTypes[2].Descriptor()
}

func (Mesh_Layer) Type() protoreflect.EnumType {
	return &file_proto_rocktree_RockTree_proto_enumTypes[2]
}

func (x Mesh_Layer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Mesh_Layer) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Mesh_Layer(num)
	return nil
}

// Deprecated: Use Mesh_Layer.Descriptor instead.
func (Mesh_Layer) EnumDescriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{17, 0}
}

// LayerMask 枚举定义图层掩码
type Mesh_LayerMask int32

const (
	Mesh_TERRAIN_WITH_OVERGROUND Mesh_LayerMask = 7   // 带地上的地形
	Mesh_TERRAIN_WITH_WATER      Mesh_LayerMask = 28  // 带水的地形
	Mesh_TERRAIN_WITHOUT_WATER   Mesh_LayerMask = 14  // 不带水的地形
	Mesh_OVERLAY_WITH_SKIRTS     Mesh_LayerMask = 384 // 带裙边的覆盖
	Mesh_WATER_WITH_SKIRTS       Mesh_LayerMask = 112 // 带裙边的水
)

// Enum value maps for Mesh_LayerMask.
var (
	Mesh_LayerMask_name = map[int32]string{
		7:   "TERRAIN_WITH_OVERGROUND",
		28:  "TERRAIN_WITH_WATER",
		14:  "TERRAIN_WITHOUT_WATER",
		384: "OVERLAY_WITH_SKIRTS",
		112: "WATER_WITH_SKIRTS",
	}
	Mesh_LayerMask_value = map[string]int32{
		"TERRAIN_WITH_OVERGROUND": 7,
		"TERRAIN_WITH_WATER":      28,
		"TERRAIN_WITHOUT_WATER":   14,
		"OVERLAY_WITH_SKIRTS":     384,
		"WATER_WITH_SKIRTS":       112,
	}
)

func (x Mesh_LayerMask) Enum() *Mesh_LayerMask {
	p := new(Mesh_LayerMask)
	*p = x
	return p
}

func (x Mesh_LayerMask) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mesh_LayerMask) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rocktree_RockTree_proto_enumTypes[3].Descriptor()
}

func (Mesh_LayerMask) Type() protoreflect.EnumType {
	return &file_proto_rocktree_RockTree_proto_enumTypes[3]
}

func (x Mesh_LayerMask) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Mesh_LayerMask) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Mesh_LayerMask(num)
	return nil
}

// Deprecated: Use Mesh_LayerMask.Descriptor instead.
func (Mesh_LayerMask) EnumDescriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{17, 1}
}

// Format 枚举定义纹理格式
type Texture_Format int32

const (
	Texture_JPG      Texture_Format = 1  // JPG格式
	Texture_DXT1     Texture_Format = 2  // DXT1压缩格式
	Texture_ETC1     Texture_Format = 3  // ETC1压缩格式
	Texture_PVRTC2   Texture_Format = 4  // PVRTC2压缩格式
	Texture_PVRTC4   Texture_Format = 5  // PVRTC4压缩格式
	Texture_CRN_DXT1 Texture_Format = 6  // CRN_DXT1压缩格式
	Texture_HETC2    Texture_Format = 10 // HETC2压缩格式
)

// Enum value maps for Texture_Format.
var (
	Texture_Format_name = map[int32]string{
		1:  "JPG",
		2:  "DXT1",
		3:  "ETC1",
		4:  "PVRTC2",
		5:  "PVRTC4",
		6:  "CRN_DXT1",
		10: "HETC2",
	}
	Texture_Format_value = map[string]int32{
		"JPG":      1,
		"DXT1":     2,
		"ETC1":     3,
		"PVRTC2":   4,
		"PVRTC4":   5,
		"CRN_DXT1": 6,
		"HETC2":    10,
	}
)

func (x Texture_Format) Enum() *Texture_Format {
	p := new(Texture_Format)
	*p = x
	return p
}

func (x Texture_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Texture_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rocktree_RockTree_proto_enumTypes[4].Descriptor()
}

func (Texture_Format) Type() protoreflect.EnumType {
	return &file_proto_rocktree_RockTree_proto_enumTypes[4]
}

func (x Texture_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Texture_Format) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Texture_Format(num)
	return nil
}

// Deprecated: Use Texture_Format.Descriptor instead.
func (Texture_Format) EnumDescriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{18, 0}
}

// ViewDirection 枚举定义视图方向
type Texture_ViewDirection int32

const (
	Texture_ANY      Texture_ViewDirection = 0 // 任意方向
	Texture_NADIR    Texture_ViewDirection = 1 // 天底方向
	Texture_NORTH_45 Texture_ViewDirection = 2 // 北45度
	Texture_EAST_45  Texture_ViewDirection = 3 // 东45度
	Texture_SOUTH_45 Texture_ViewDirection = 4 // 南45度
	Texture_WEST_45  Texture_ViewDirection = 5 // 西45度
)

// Enum value maps for Texture_ViewDirection.
var (
	Texture_ViewDirection_name = map[int32]string{
		0: "ANY",
		1: "NADIR",
		2: "NORTH_45",
		3: "EAST_45",
		4: "SOUTH_45",
		5: "WEST_45",
	}
	Texture_ViewDirection_value = map[string]int32{
		"ANY":      0,
		"NADIR":    1,
		"NORTH_45": 2,
		"EAST_45":  3,
		"SOUTH_45": 4,
		"WEST_45":  5,
	}
)

func (x Texture_ViewDirection) Enum() *Texture_ViewDirection {
	p := new(Texture_ViewDirection)
	*p = x
	return p
}

func (x Texture_ViewDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Texture_ViewDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rocktree_RockTree_proto_enumTypes[5].Descriptor()
}

func (Texture_ViewDirection) Type() protoreflect.EnumType {
	return &file_proto_rocktree_RockTree_proto_enumTypes[5]
}

func (x Texture_ViewDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Texture_ViewDirection) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Texture_ViewDirection(num)
	return nil
}

// Deprecated: Use Texture_ViewDirection.Descriptor instead.
func (Texture_ViewDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{18, 1}
}

// TileKeyBounds 定义瓦片键的边界范围
type TileKeyBounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         *uint32                `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`                          // 瓦片层级
	MinRow        *uint32                `protobuf:"varint,2,opt,name=min_row,json=minRow" json:"min_row,omitempty"`          // 最小行号
	MinColumn     *uint32                `protobuf:"varint,3,opt,name=min_column,json=minColumn" json:"min_column,omitempty"` // 最小列号
	MaxRow        *uint32                `protobuf:"varint,4,opt,name=max_row,json=maxRow" json:"max_row,omitempty"`          // 最大行号
	MaxColumn     *uint32                `protobuf:"varint,5,opt,name=max_column,json=maxColumn" json:"max_column,omitempty"` // 最大列号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TileKeyBounds) Reset() {
	*x = TileKeyBounds{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TileKeyBounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileKeyBounds) ProtoMessage() {}

func (x *TileKeyBounds) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileKeyBounds.ProtoReflect.Descriptor instead.
func (*TileKeyBounds) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{0}
}

func (x *TileKeyBounds) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *TileKeyBounds) GetMinRow() uint32 {
	if x != nil && x.MinRow != nil {
		return *x.MinRow
	}
	return 0
}

func (x *TileKeyBounds) GetMinColumn() uint32 {
	if x != nil && x.MinColumn != nil {
		return *x.MinColumn
	}
	return 0
}

func (x *TileKeyBounds) GetMaxRow() uint32 {
	if x != nil && x.MaxRow != nil {
		return *x.MaxRow
	}
	return 0
}

func (x *TileKeyBounds) GetMaxColumn() uint32 {
	if x != nil && x.MaxColumn != nil {
		return *x.MaxColumn
	}
	return 0
}

// KmlCoordinate 定义 KML 坐标点
type KmlCoordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      *float64               `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`   // 纬度
	Longitude     *float64               `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"` // 经度
	Altitude      *float64               `protobuf:"fixed64,3,opt,name=altitude" json:"altitude,omitempty"`   // 海拔高度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KmlCoordinate) Reset() {
	*x = KmlCoordinate{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KmlCoordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KmlCoordinate) ProtoMessage() {}

func (x *KmlCoordinate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KmlCoordinate.ProtoReflect.Descriptor instead.
func (*KmlCoordinate) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{1}
}

func (x *KmlCoordinate) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *KmlCoordinate) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *KmlCoordinate) GetAltitude() float64 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

// ViewportMetadataRequest 定义视口元数据请求
type ViewportMetadataRequest struct {
	state                        protoimpl.MessageState                            `protogen:"open.v1"`
	Epoch                        *uint32                                           `protobuf:"varint,1,opt,name=epoch" json:"epoch,omitempty"`                                                                                                                                                      // 时间戳（纪元）
	TileKeyBounds                []*TileKeyBounds                                  `protobuf:"bytes,2,rep,name=tile_key_bounds,json=tileKeyBounds" json:"tile_key_bounds,omitempty"`                                                                                                                // 瓦片键边界范围列表
	OmitAncestors                *bool                                             `protobuf:"varint,3,opt,name=omit_ancestors,json=omitAncestors" json:"omit_ancestors,omitempty"`                                                                                                                 // 是否忽略祖先节点
	BulkMetadataResponseMode     *ViewportMetadataRequest_BulkMetadataResponseMode `protobuf:"varint,4,opt,name=bulk_metadata_response_mode,json=bulkMetadataResponseMode,enum=GoogleEarth.RockTree.ViewportMetadataRequest_BulkMetadataResponseMode" json:"bulk_metadata_response_mode,omitempty"` // 批量元数据响应模式
	TerrainElevationCoords       []*KmlCoordinate                                  `protobuf:"bytes,5,rep,name=terrain_elevation_coords,json=terrainElevationCoords" json:"terrain_elevation_coords,omitempty"`                                                                                     // 地形高程坐标列表
	BulkMetadataSpdyPushPriority *uint32                                           `protobuf:"varint,6,opt,name=bulk_metadata_spdy_push_priority,json=bulkMetadataSpdyPushPriority,def=7" json:"bulk_metadata_spdy_push_priority,omitempty"`                                                        // 批量元数据 SPDY 推送优先级，默认值为 7
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

// Default values for ViewportMetadataRequest fields.
const (
	Default_ViewportMetadataRequest_BulkMetadataSpdyPushPriority = uint32(7)
)

func (x *ViewportMetadataRequest) Reset() {
	*x = ViewportMetadataRequest{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewportMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewportMetadataRequest) ProtoMessage() {}

func (x *ViewportMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewportMetadataRequest.ProtoReflect.Descriptor instead.
func (*ViewportMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{2}
}

func (x *ViewportMetadataRequest) GetEpoch() uint32 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *ViewportMetadataRequest) GetTileKeyBounds() []*TileKeyBounds {
	if x != nil {
		return x.TileKeyBounds
	}
	return nil
}

func (x *ViewportMetadataRequest) GetOmitAncestors() bool {
	if x != nil && x.OmitAncestors != nil {
		return *x.OmitAncestors
	}
	return false
}

func (x *ViewportMetadataRequest) GetBulkMetadataResponseMode() ViewportMetadataRequest_BulkMetadataResponseMode {
	if x != nil && x.BulkMetadataResponseMode != nil {
		return *x.BulkMetadataResponseMode
	}
	return ViewportMetadataRequest_NONE
}

func (x *ViewportMetadataRequest) GetTerrainElevationCoords() []*KmlCoordinate {
	if x != nil {
		return x.TerrainElevationCoords
	}
	return nil
}

func (x *ViewportMetadataRequest) GetBulkMetadataSpdyPushPriority() uint32 {
	if x != nil && x.BulkMetadataSpdyPushPriority != nil {
		return *x.BulkMetadataSpdyPushPriority
	}
	return Default_ViewportMetadataRequest_BulkMetadataSpdyPushPriority
}

// ViewportMetadata 定义视口元数据
type ViewportMetadata struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PlanetoidMetadata      *PlanetoidMetadata     `protobuf:"bytes,1,opt,name=planetoid_metadata,json=planetoidMetadata" json:"planetoid_metadata,omitempty"`                  // 行星体元数据
	BulkMetadataKeys       []*NodeKey             `protobuf:"bytes,2,rep,name=bulk_metadata_keys,json=bulkMetadataKeys" json:"bulk_metadata_keys,omitempty"`                   // 批量元数据键列表
	TerrainElevationCoords []*KmlCoordinate       `protobuf:"bytes,3,rep,name=terrain_elevation_coords,json=terrainElevationCoords" json:"terrain_elevation_coords,omitempty"` // 地形高程坐标列表
	BulkMetadata           []*BulkMetadata        `protobuf:"bytes,4,rep,name=bulk_metadata,json=bulkMetadata" json:"bulk_metadata,omitempty"`                                 // 批量元数据列表
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ViewportMetadata) Reset() {
	*x = ViewportMetadata{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewportMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewportMetadata) ProtoMessage() {}

func (x *ViewportMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewportMetadata.ProtoReflect.Descriptor instead.
func (*ViewportMetadata) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{3}
}

func (x *ViewportMetadata) GetPlanetoidMetadata() *PlanetoidMetadata {
	if x != nil {
		return x.PlanetoidMetadata
	}
	return nil
}

func (x *ViewportMetadata) GetBulkMetadataKeys() []*NodeKey {
	if x != nil {
		return x.BulkMetadataKeys
	}
	return nil
}

func (x *ViewportMetadata) GetTerrainElevationCoords() []*KmlCoordinate {
	if x != nil {
		return x.TerrainElevationCoords
	}
	return nil
}

func (x *ViewportMetadata) GetBulkMetadata() []*BulkMetadata {
	if x != nil {
		return x.BulkMetadata
	}
	return nil
}

// BulkMetadataRequest 定义批量元数据请求
type BulkMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeKey       *NodeKey               `protobuf:"bytes,1,opt,name=node_key,json=nodeKey" json:"node_key,omitempty"` // 节点键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkMetadataRequest) Reset() {
	*x = BulkMetadataRequest{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkMetadataRequest) ProtoMessage() {}

func (x *BulkMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkMetadataRequest.ProtoReflect.Descriptor instead.
func (*BulkMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{4}
}

func (x *BulkMetadataRequest) GetNodeKey() *NodeKey {
	if x != nil {
		return x.NodeKey
	}
	return nil
}

// NodeDataRequest 定义节点数据请求
type NodeDataRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeKey         *NodeKey               `protobuf:"bytes,1,opt,name=node_key,json=nodeKey" json:"node_key,omitempty"`                                                             // 节点键
	TextureFormat   *Texture_Format        `protobuf:"varint,2,opt,name=texture_format,json=textureFormat,enum=GoogleEarth.RockTree.Texture_Format" json:"texture_format,omitempty"` // 纹理格式
	ImageryEpoch    *uint32                `protobuf:"varint,3,opt,name=imagery_epoch,json=imageryEpoch" json:"imagery_epoch,omitempty"`                                             // 影像纪元
	OmitTexture     *bool                  `protobuf:"varint,4,opt,name=omit_texture,json=omitTexture" json:"omit_texture,omitempty"`                                                // 是否忽略纹理
	Date            *int32                 `protobuf:"varint,5,opt,name=date" json:"date,omitempty"`                                                                                 // 日期
	Milliseconds    *int32                 `protobuf:"varint,6,opt,name=milliseconds" json:"milliseconds,omitempty"`                                                                 // 毫秒
	TextureIsShared *bool                  `protobuf:"varint,7,opt,name=texture_is_shared,json=textureIsShared" json:"texture_is_shared,omitempty"`                                  // 纹理是否共享
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeDataRequest) Reset() {
	*x = NodeDataRequest{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDataRequest) ProtoMessage() {}

func (x *NodeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDataRequest.ProtoReflect.Descriptor instead.
func (*NodeDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{5}
}

func (x *NodeDataRequest) GetNodeKey() *NodeKey {
	if x != nil {
		return x.NodeKey
	}
	return nil
}

func (x *NodeDataRequest) GetTextureFormat() Texture_Format {
	if x != nil && x.TextureFormat != nil {
		return *x.TextureFormat
	}
	return Texture_JPG
}

func (x *NodeDataRequest) GetImageryEpoch() uint32 {
	if x != nil && x.ImageryEpoch != nil {
		return *x.ImageryEpoch
	}
	return 0
}

func (x *NodeDataRequest) GetOmitTexture() bool {
	if x != nil && x.OmitTexture != nil {
		return *x.OmitTexture
	}
	return false
}

func (x *NodeDataRequest) GetDate() int32 {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return 0
}

func (x *NodeDataRequest) GetMilliseconds() int32 {
	if x != nil && x.Milliseconds != nil {
		return *x.Milliseconds
	}
	return 0
}

func (x *NodeDataRequest) GetTextureIsShared() bool {
	if x != nil && x.TextureIsShared != nil {
		return *x.TextureIsShared
	}
	return false
}

// NodeKey 定义节点键
type NodeKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`    // 路径
	Epoch         *uint32                `protobuf:"varint,2,opt,name=epoch" json:"epoch,omitempty"` // 纪元
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeKey) Reset() {
	*x = NodeKey{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeKey) ProtoMessage() {}

func (x *NodeKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeKey.ProtoReflect.Descriptor instead.
func (*NodeKey) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{6}
}

func (x *NodeKey) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *NodeKey) GetEpoch() uint32 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

// RockTreeTasks 对应 RockTreeTasks 结构体
type RockTreeTasks struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	HeadNodeKey                    *NodeKey               `protobuf:"bytes,1,opt,name=head_node_key,json=headNodeKey" json:"head_node_key,omitempty"`                                                             // 头节点键 *NodeKey
	NodeMetadataTasks              []*NodeMetadataTasks   `protobuf:"bytes,2,rep,name=node_metadata_tasks,json=nodeMetadataTasks" json:"node_metadata_tasks,omitempty"`                                           // 节点元数据任务列表 []*NodeMetadataTasks
	DefaultImageryEpoch            *uint32                `protobuf:"varint,3,opt,name=default_imagery_epoch,json=defaultImageryEpoch" json:"default_imagery_epoch,omitempty"`                                    // 默认影像纪元 *uint32
	DefaultAvailableTextureFormats *uint32                `protobuf:"varint,4,opt,name=default_available_texture_formats,json=defaultAvailableTextureFormats" json:"default_available_texture_formats,omitempty"` // 默认可用纹理格式 *uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *RockTreeTasks) Reset() {
	*x = RockTreeTasks{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RockTreeTasks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RockTreeTasks) ProtoMessage() {}

func (x *RockTreeTasks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RockTreeTasks.ProtoReflect.Descriptor instead.
func (*RockTreeTasks) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{7}
}

func (x *RockTreeTasks) GetHeadNodeKey() *NodeKey {
	if x != nil {
		return x.HeadNodeKey
	}
	return nil
}

func (x *RockTreeTasks) GetNodeMetadataTasks() []*NodeMetadataTasks {
	if x != nil {
		return x.NodeMetadataTasks
	}
	return nil
}

func (x *RockTreeTasks) GetDefaultImageryEpoch() uint32 {
	if x != nil && x.DefaultImageryEpoch != nil {
		return *x.DefaultImageryEpoch
	}
	return 0
}

func (x *RockTreeTasks) GetDefaultAvailableTextureFormats() uint32 {
	if x != nil && x.DefaultAvailableTextureFormats != nil {
		return *x.DefaultAvailableTextureFormats
	}
	return 0
}

// NodeMetadataTasks 对应 NodeMetadataTasks 结构体
type NodeMetadataTasks struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	PathAndFlags            *uint32                `protobuf:"varint,1,opt,name=path_and_flags,json=pathAndFlags" json:"path_and_flags,omitempty"`                                  // 路径和标志 *uint32
	Epoch                   *uint32                `protobuf:"varint,2,opt,name=epoch" json:"epoch,omitempty"`                                                                      // 纪元 *uint32
	BulkMetadataEpoch       *uint32                `protobuf:"varint,3,opt,name=bulk_metadata_epoch,json=bulkMetadataEpoch" json:"bulk_metadata_epoch,omitempty"`                   // 批量元数据纪元 *uint32
	ImageryEpoch            *uint32                `protobuf:"varint,4,opt,name=imagery_epoch,json=imageryEpoch" json:"imagery_epoch,omitempty"`                                    // 影像纪元 *uint32
	AvailableTextureFormats *uint32                `protobuf:"varint,5,opt,name=available_texture_formats,json=availableTextureFormats" json:"available_texture_formats,omitempty"` // 可用纹理格式 *uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NodeMetadataTasks) Reset() {
	*x = NodeMetadataTasks{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetadataTasks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetadataTasks) ProtoMessage() {}

func (x *NodeMetadataTasks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetadataTasks.ProtoReflect.Descriptor instead.
func (*NodeMetadataTasks) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{8}
}

func (x *NodeMetadataTasks) GetPathAndFlags() uint32 {
	if x != nil && x.PathAndFlags != nil {
		return *x.PathAndFlags
	}
	return 0
}

func (x *NodeMetadataTasks) GetEpoch() uint32 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *NodeMetadataTasks) GetBulkMetadataEpoch() uint32 {
	if x != nil && x.BulkMetadataEpoch != nil {
		return *x.BulkMetadataEpoch
	}
	return 0
}

func (x *NodeMetadataTasks) GetImageryEpoch() uint32 {
	if x != nil && x.ImageryEpoch != nil {
		return *x.ImageryEpoch
	}
	return 0
}

func (x *NodeMetadataTasks) GetAvailableTextureFormats() uint32 {
	if x != nil && x.AvailableTextureFormats != nil {
		return *x.AvailableTextureFormats
	}
	return 0
}

// CopyrightRequest 定义版权请求
type CopyrightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         *uint32                `protobuf:"varint,1,opt,name=epoch" json:"epoch,omitempty"` // 纪元
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyrightRequest) Reset() {
	*x = CopyrightRequest{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyrightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyrightRequest) ProtoMessage() {}

func (x *CopyrightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyrightRequest.ProtoReflect.Descriptor instead.
func (*CopyrightRequest) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{9}
}

func (x *CopyrightRequest) GetEpoch() uint32 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

// TextureDataRequest 定义纹理数据请求
type TextureDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeKey       *NodeKey               `protobuf:"bytes,1,opt,name=node_key,json=nodeKey" json:"node_key,omitempty"`                                                                    // 节点键
	TextureFormat *Texture_Format        `protobuf:"varint,2,opt,name=texture_format,json=textureFormat,enum=GoogleEarth.RockTree.Texture_Format" json:"texture_format,omitempty"`        // 纹理格式
	ViewDirection *Texture_ViewDirection `protobuf:"varint,3,opt,name=view_direction,json=viewDirection,enum=GoogleEarth.RockTree.Texture_ViewDirection" json:"view_direction,omitempty"` // 视图方向
	ImageryEpoch  *uint32                `protobuf:"varint,4,opt,name=imagery_epoch,json=imageryEpoch" json:"imagery_epoch,omitempty"`                                                    // 影像纪元
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextureDataRequest) Reset() {
	*x = TextureDataRequest{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextureDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextureDataRequest) ProtoMessage() {}

func (x *TextureDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextureDataRequest.ProtoReflect.Descriptor instead.
func (*TextureDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{10}
}

func (x *TextureDataRequest) GetNodeKey() *NodeKey {
	if x != nil {
		return x.NodeKey
	}
	return nil
}

func (x *TextureDataRequest) GetTextureFormat() Texture_Format {
	if x != nil && x.TextureFormat != nil {
		return *x.TextureFormat
	}
	return Texture_JPG
}

func (x *TextureDataRequest) GetViewDirection() Texture_ViewDirection {
	if x != nil && x.ViewDirection != nil {
		return *x.ViewDirection
	}
	return Texture_ANY
}

func (x *TextureDataRequest) GetImageryEpoch() uint32 {
	if x != nil && x.ImageryEpoch != nil {
		return *x.ImageryEpoch
	}
	return 0
}

// BulkMetadata 定义批量元数据
type BulkMetadata struct {
	state                                       protoimpl.MessageState `protogen:"open.v1"`
	NodeMetadata                                []*NodeMetadata        `protobuf:"bytes,1,rep,name=node_metadata,json=nodeMetadata" json:"node_metadata,omitempty"`                                                                                                       // 节点元数据列表
	HeadNodeKey                                 *NodeKey               `protobuf:"bytes,2,opt,name=head_node_key,json=headNodeKey" json:"head_node_key,omitempty"`                                                                                                        // 头节点键值
	HeadNodeCenter                              []float64              `protobuf:"fixed64,3,rep,packed,name=head_node_center,json=headNodeCenter" json:"head_node_center,omitempty"`                                                                                      // 头节点中心坐标(x,y,z)
	MetersPerTexel                              []float32              `protobuf:"fixed32,4,rep,packed,name=meters_per_texel,json=metersPerTexel" json:"meters_per_texel,omitempty"`                                                                                      // 每个纹理像素对应的米数(用于LOD计算)
	DefaultImageryEpoch                         *uint32                `protobuf:"varint,5,opt,name=default_imagery_epoch,json=defaultImageryEpoch" json:"default_imagery_epoch,omitempty"`                                                                               // 默认图像纪元(版本)
	DefaultAvailableTextureFormats              *uint32                `protobuf:"varint,6,opt,name=default_available_texture_formats,json=defaultAvailableTextureFormats" json:"default_available_texture_formats,omitempty"`                                            // 默认可用的纹理格式
	DefaultAvailableViewDependentTextures       *uint32                `protobuf:"varint,7,opt,name=default_available_view_dependent_textures,json=defaultAvailableViewDependentTextures" json:"default_available_view_dependent_textures,omitempty"`                     // 默认可用的视图相关纹理
	DefaultAvailableViewDependentTextureFormats *uint32                `protobuf:"varint,8,opt,name=default_available_view_dependent_texture_formats,json=defaultAvailableViewDependentTextureFormats" json:"default_available_view_dependent_texture_formats,omitempty"` // 默认可用的视图相关纹理格式
	CommonDatedNodes                            []*DatedNode           `protobuf:"bytes,9,rep,name=common_dated_nodes,json=commonDatedNodes" json:"common_dated_nodes,omitempty"`                                                                                         // 共享的日期节点列表
	DefaultAcquisitionDateRange                 *AcquisitionDateRange  `protobuf:"bytes,10,opt,name=default_acquisition_date_range,json=defaultAcquisitionDateRange" json:"default_acquisition_date_range,omitempty"`                                                     // 默认采集日期范围
	unknownFields                               protoimpl.UnknownFields
	sizeCache                                   protoimpl.SizeCache
}

func (x *BulkMetadata) Reset() {
	*x = BulkMetadata{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkMetadata) ProtoMessage() {}

func (x *BulkMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkMetadata.ProtoReflect.Descriptor instead.
func (*BulkMetadata) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{11}
}

func (x *BulkMetadata) GetNodeMetadata() []*NodeMetadata {
	if x != nil {
		return x.NodeMetadata
	}
	return nil
}

func (x *BulkMetadata) GetHeadNodeKey() *NodeKey {
	if x != nil {
		return x.HeadNodeKey
	}
	return nil
}

func (x *BulkMetadata) GetHeadNodeCenter() []float64 {
	if x != nil {
		return x.HeadNodeCenter
	}
	return nil
}

func (x *BulkMetadata) GetMetersPerTexel() []float32 {
	if x != nil {
		return x.MetersPerTexel
	}
	return nil
}

func (x *BulkMetadata) GetDefaultImageryEpoch() uint32 {
	if x != nil && x.DefaultImageryEpoch != nil {
		return *x.DefaultImageryEpoch
	}
	return 0
}

func (x *BulkMetadata) GetDefaultAvailableTextureFormats() uint32 {
	if x != nil && x.DefaultAvailableTextureFormats != nil {
		return *x.DefaultAvailableTextureFormats
	}
	return 0
}

func (x *BulkMetadata) GetDefaultAvailableViewDependentTextures() uint32 {
	if x != nil && x.DefaultAvailableViewDependentTextures != nil {
		return *x.DefaultAvailableViewDependentTextures
	}
	return 0
}

func (x *BulkMetadata) GetDefaultAvailableViewDependentTextureFormats() uint32 {
	if x != nil && x.DefaultAvailableViewDependentTextureFormats != nil {
		return *x.DefaultAvailableViewDependentTextureFormats
	}
	return 0
}

func (x *BulkMetadata) GetCommonDatedNodes() []*DatedNode {
	if x != nil {
		return x.CommonDatedNodes
	}
	return nil
}

func (x *BulkMetadata) GetDefaultAcquisitionDateRange() *AcquisitionDateRange {
	if x != nil {
		return x.DefaultAcquisitionDateRange
	}
	return nil
}

// NodeMetadata 存储空间节点的元数据信息，包含几何属性、时间戳、纹理格式等关键参数
type NodeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path_and_flags 路径标识组合字段：
	// - 高24位表示路径长度（单位：字节）
	// - 低8位为标志位（参考Flags枚举）
	PathAndFlags *uint32 `protobuf:"varint,1,opt,name=path_and_flags,json=pathAndFlags" json:"path_and_flags,omitempty"`
	// epoch 元数据版本时间戳（单位：秒，自Unix纪元）
	Epoch *uint32 `protobuf:"varint,2,opt,name=epoch" json:"epoch,omitempty"`
	// bulk_metadata_epoch 批量处理时的元数据时间戳
	// 用于协调大规模数据更新操作
	BulkMetadataEpoch *uint32 `protobuf:"varint,5,opt,name=bulk_metadata_epoch,json=bulkMetadataEpoch" json:"bulk_metadata_epoch,omitempty"`
	// oriented_bounding_box 定向包围盒数据
	// 格式：[x_center, y_center, z_center, x_extent, y_extent, z_extent, rotation_matrix_3x3]
	// 使用64位浮点数序列化
	OrientedBoundingBox []byte `protobuf:"bytes,3,opt,name=oriented_bounding_box,json=orientedBoundingBox" json:"oriented_bounding_box,omitempty"`
	// meters_per_texel 空间分辨率
	// 表示每个纹理像素对应的实际地理尺寸（单位：米）
	MetersPerTexel *float32 `protobuf:"fixed32,4,opt,name=meters_per_texel,json=metersPerTexel" json:"meters_per_texel,omitempty"`
	// processing_oriented_bounding_box 处理专用包围盒
	// 格式：[min_x, min_y, min_z, max_x, max_y, max_z]
	// 使用WGS84坐标系存储双精度坐标
	ProcessingOrientedBoundingBox []float64 `protobuf:"fixed64,6,rep,packed,name=processing_oriented_bounding_box,json=processingOrientedBoundingBox" json:"processing_oriented_bounding_box,omitempty"`
	// imagery_epoch 影像数据时间戳
	// 当USE_IMAGERY_EPOCH标志置位时生效
	ImageryEpoch *uint32 `protobuf:"varint,7,opt,name=imagery_epoch,json=imageryEpoch" json:"imagery_epoch,omitempty"`
	// available_texture_formats 可用纹理格式掩码
	// 按位表示支持的纹理格式（参考TextureFormat枚举）
	AvailableTextureFormats *uint32 `protobuf:"varint,8,opt,name=available_texture_formats,json=availableTextureFormats" json:"available_texture_formats,omitempty"`
	// available_view_dependent_textures 视角相关纹理数量
	// 表示支持的动态视角纹理实例数
	AvailableViewDependentTextures *uint32 `protobuf:"varint,9,opt,name=available_view_dependent_textures,json=availableViewDependentTextures" json:"available_view_dependent_textures,omitempty"`
	// available_view_dependent_texture_formats 视角相关纹理格式掩码
	// 按位表示支持的视角相关纹理格式
	AvailableViewDependentTextureFormats *uint32 `protobuf:"varint,10,opt,name=available_view_dependent_texture_formats,json=availableViewDependentTextureFormats" json:"available_view_dependent_texture_formats,omitempty"`
	// dated_nodes 时间关联子节点列表
	// 每个条目对应特定时间点的子节点状态
	DatedNodes []*DatedNode `protobuf:"bytes,11,rep,name=dated_nodes,json=datedNodes" json:"dated_nodes,omitempty"`
	// acquisition_date_range 数据采集时间范围
	// 用于标注该节点对应数据的采集时间段
	AcquisitionDateRange *AcquisitionDateRange `protobuf:"bytes,12,opt,name=acquisition_date_range,json=acquisitionDateRange" json:"acquisition_date_range,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeMetadata) Reset() {
	*x = NodeMetadata{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetadata) ProtoMessage() {}

func (x *NodeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetadata.ProtoReflect.Descriptor instead.
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{12}
}

func (x *NodeMetadata) GetPathAndFlags() uint32 {
	if x != nil && x.PathAndFlags != nil {
		return *x.PathAndFlags
	}
	return 0
}

func (x *NodeMetadata) GetEpoch() uint32 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *NodeMetadata) GetBulkMetadataEpoch() uint32 {
	if x != nil && x.BulkMetadataEpoch != nil {
		return *x.BulkMetadataEpoch
	}
	return 0
}

func (x *NodeMetadata) GetOrientedBoundingBox() []byte {
	if x != nil {
		return x.OrientedBoundingBox
	}
	return nil
}

func (x *NodeMetadata) GetMetersPerTexel() float32 {
	if x != nil && x.MetersPerTexel != nil {
		return *x.MetersPerTexel
	}
	return 0
}

func (x *NodeMetadata) GetProcessingOrientedBoundingBox() []float64 {
	if x != nil {
		return x.ProcessingOrientedBoundingBox
	}
	return nil
}

func (x *NodeMetadata) GetImageryEpoch() uint32 {
	if x != nil && x.ImageryEpoch != nil {
		return *x.ImageryEpoch
	}
	return 0
}

func (x *NodeMetadata) GetAvailableTextureFormats() uint32 {
	if x != nil && x.AvailableTextureFormats != nil {
		return *x.AvailableTextureFormats
	}
	return 0
}

func (x *NodeMetadata) GetAvailableViewDependentTextures() uint32 {
	if x != nil && x.AvailableViewDependentTextures != nil {
		return *x.AvailableViewDependentTextures
	}
	return 0
}

func (x *NodeMetadata) GetAvailableViewDependentTextureFormats() uint32 {
	if x != nil && x.AvailableViewDependentTextureFormats != nil {
		return *x.AvailableViewDependentTextureFormats
	}
	return 0
}

func (x *NodeMetadata) GetDatedNodes() []*DatedNode {
	if x != nil {
		return x.DatedNodes
	}
	return nil
}

func (x *NodeMetadata) GetAcquisitionDateRange() *AcquisitionDateRange {
	if x != nil {
		return x.AcquisitionDateRange
	}
	return nil
}

// DatedNode 定义带日期的节点
type DatedNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *uint32                `protobuf:"varint,1,opt,name=date" json:"date,omitempty"`                                  // 日期
	Milliseconds  *uint32                `protobuf:"varint,2,opt,name=milliseconds" json:"milliseconds,omitempty"`                  // 毫秒
	Epoch         *int32                 `protobuf:"varint,3,opt,name=epoch" json:"epoch,omitempty"`                                // 纪元
	SharedEpoch   *int32                 `protobuf:"varint,5,opt,name=shared_epoch,json=sharedEpoch" json:"shared_epoch,omitempty"` // 共享纪元
	CoarseLevel   *int32                 `protobuf:"varint,4,opt,name=coarse_level,json=coarseLevel" json:"coarse_level,omitempty"` // 粗略层级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatedNode) Reset() {
	*x = DatedNode{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatedNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatedNode) ProtoMessage() {}

func (x *DatedNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatedNode.ProtoReflect.Descriptor instead.
func (*DatedNode) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{13}
}

func (x *DatedNode) GetDate() uint32 {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return 0
}

func (x *DatedNode) GetMilliseconds() uint32 {
	if x != nil && x.Milliseconds != nil {
		return *x.Milliseconds
	}
	return 0
}

func (x *DatedNode) GetEpoch() int32 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *DatedNode) GetSharedEpoch() int32 {
	if x != nil && x.SharedEpoch != nil {
		return *x.SharedEpoch
	}
	return 0
}

func (x *DatedNode) GetCoarseLevel() int32 {
	if x != nil && x.CoarseLevel != nil {
		return *x.CoarseLevel
	}
	return 0
}

// AcquisitionDate 定义采集日期
type AcquisitionDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *uint32                `protobuf:"varint,1,opt,name=date" json:"date,omitempty"`                 // 日期
	Milliseconds  *uint32                `protobuf:"varint,2,opt,name=milliseconds" json:"milliseconds,omitempty"` // 毫秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquisitionDate) Reset() {
	*x = AcquisitionDate{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquisitionDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquisitionDate) ProtoMessage() {}

func (x *AcquisitionDate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquisitionDate.ProtoReflect.Descriptor instead.
func (*AcquisitionDate) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{14}
}

func (x *AcquisitionDate) GetDate() uint32 {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return 0
}

func (x *AcquisitionDate) GetMilliseconds() uint32 {
	if x != nil && x.Milliseconds != nil {
		return *x.Milliseconds
	}
	return 0
}

// AcquisitionDateRange 定义采集日期范围
type AcquisitionDateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Begin         *AcquisitionDate       `protobuf:"bytes,1,opt,name=begin" json:"begin,omitempty"` // 开始日期
	End           *AcquisitionDate       `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`     // 结束日期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquisitionDateRange) Reset() {
	*x = AcquisitionDateRange{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquisitionDateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquisitionDateRange) ProtoMessage() {}

func (x *AcquisitionDateRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquisitionDateRange.ProtoReflect.Descriptor instead.
func (*AcquisitionDateRange) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{15}
}

func (x *AcquisitionDateRange) GetBegin() *AcquisitionDate {
	if x != nil {
		return x.Begin
	}
	return nil
}

func (x *AcquisitionDateRange) GetEnd() *AcquisitionDate {
	if x != nil {
		return x.End
	}
	return nil
}

// NodeData 定义节点数据
type NodeData struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MatrixGlobeFromMesh  []float64              `protobuf:"fixed64,1,rep,packed,name=matrix_globe_from_mesh,json=matrixGlobeFromMesh" json:"matrix_globe_from_mesh,omitempty"` // 从网格到地球的变换矩阵
	Meshes               []*Mesh                `protobuf:"bytes,2,rep,name=meshes" json:"meshes,omitempty"`                                                                   // 网格列表
	CopyrightIds         []uint32               `protobuf:"varint,3,rep,name=copyright_ids,json=copyrightIds" json:"copyright_ids,omitempty"`                                  // 版权ID列表
	NodeKey              *NodeKey               `protobuf:"bytes,4,opt,name=node_key,json=nodeKey" json:"node_key,omitempty"`                                                  // 节点键
	KmlBoundingBox       []float64              `protobuf:"fixed64,5,rep,packed,name=kml_bounding_box,json=kmlBoundingBox" json:"kml_bounding_box,omitempty"`                  // KML边界框
	WaterMesh            *Mesh                  `protobuf:"bytes,6,opt,name=water_mesh,json=waterMesh" json:"water_mesh,omitempty"`                                            // 水面网格
	OverlaySurfaceMeshes []*Mesh                `protobuf:"bytes,7,rep,name=overlay_surface_meshes,json=overlaySurfaceMeshes" json:"overlay_surface_meshes,omitempty"`         // 覆盖面网格列表
	NormalTable          []byte                 `protobuf:"bytes,8,opt,name=normal_table,json=normalTable" json:"normal_table,omitempty"`                                      // 法线表
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeData) Reset() {
	*x = NodeData{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeData) ProtoMessage() {}

func (x *NodeData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeData.ProtoReflect.Descriptor instead.
func (*NodeData) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{16}
}

func (x *NodeData) GetMatrixGlobeFromMesh() []float64 {
	if x != nil {
		return x.MatrixGlobeFromMesh
	}
	return nil
}

func (x *NodeData) GetMeshes() []*Mesh {
	if x != nil {
		return x.Meshes
	}
	return nil
}

func (x *NodeData) GetCopyrightIds() []uint32 {
	if x != nil {
		return x.CopyrightIds
	}
	return nil
}

func (x *NodeData) GetNodeKey() *NodeKey {
	if x != nil {
		return x.NodeKey
	}
	return nil
}

func (x *NodeData) GetKmlBoundingBox() []float64 {
	if x != nil {
		return x.KmlBoundingBox
	}
	return nil
}

func (x *NodeData) GetWaterMesh() *Mesh {
	if x != nil {
		return x.WaterMesh
	}
	return nil
}

func (x *NodeData) GetOverlaySurfaceMeshes() []*Mesh {
	if x != nil {
		return x.OverlaySurfaceMeshes
	}
	return nil
}

func (x *NodeData) GetNormalTable() []byte {
	if x != nil {
		return x.NormalTable
	}
	return nil
}

// Mesh 定义网格
type Mesh struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Vertices             []byte                 `protobuf:"bytes,1,opt,name=vertices" json:"vertices,omitempty"`                                                         // 顶点数据
	VertexAlphas         []byte                 `protobuf:"bytes,9,opt,name=vertex_alphas,json=vertexAlphas" json:"vertex_alphas,omitempty"`                             // 顶点透明度
	TextureCoords        []byte                 `protobuf:"bytes,2,opt,name=texture_coords,json=textureCoords" json:"texture_coords,omitempty"`                          // 纹理坐标
	Indices              []byte                 `protobuf:"bytes,3,opt,name=indices" json:"indices,omitempty"`                                                           // 索引数据
	OctantRanges         []byte                 `protobuf:"bytes,4,opt,name=octant_ranges,json=octantRanges" json:"octant_ranges,omitempty"`                             // 八分体范围
	LayerCounts          []byte                 `protobuf:"bytes,5,opt,name=layer_counts,json=layerCounts" json:"layer_counts,omitempty"`                                // 图层计数
	Texture              []*Texture             `protobuf:"bytes,6,rep,name=texture" json:"texture,omitempty"`                                                           // 纹理列表
	TextureCoordinates   []byte                 `protobuf:"bytes,7,opt,name=texture_coordinates,json=textureCoordinates" json:"texture_coordinates,omitempty"`           // 纹理坐标
	UvOffsetAndScale     []float32              `protobuf:"fixed32,10,rep,packed,name=uv_offset_and_scale,json=uvOffsetAndScale" json:"uv_offset_and_scale,omitempty"`   // UV偏移和缩放
	LayerAndOctantCounts []byte                 `protobuf:"bytes,8,opt,name=layer_and_octant_counts,json=layerAndOctantCounts" json:"layer_and_octant_counts,omitempty"` // 图层和八分体计数
	Normals              []byte                 `protobuf:"bytes,11,opt,name=normals" json:"normals,omitempty"`                                                          // 法线数据
	NormalsDev           []byte                 `protobuf:"bytes,16,opt,name=normals_dev,json=normalsDev" json:"normals_dev,omitempty"`                                  // 法线偏差
	MeshId               *uint32                `protobuf:"varint,12,opt,name=mesh_id,json=meshId" json:"mesh_id,omitempty"`                                             // 网格ID
	SkirtFlags           []byte                 `protobuf:"bytes,13,opt,name=skirt_flags,json=skirtFlags" json:"skirt_flags,omitempty"`                                  // 裙边标志
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Mesh) Reset() {
	*x = Mesh{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mesh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mesh) ProtoMessage() {}

func (x *Mesh) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mesh.ProtoReflect.Descriptor instead.
func (*Mesh) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{17}
}

func (x *Mesh) GetVertices() []byte {
	if x != nil {
		return x.Vertices
	}
	return nil
}

func (x *Mesh) GetVertexAlphas() []byte {
	if x != nil {
		return x.VertexAlphas
	}
	return nil
}

func (x *Mesh) GetTextureCoords() []byte {
	if x != nil {
		return x.TextureCoords
	}
	return nil
}

func (x *Mesh) GetIndices() []byte {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *Mesh) GetOctantRanges() []byte {
	if x != nil {
		return x.OctantRanges
	}
	return nil
}

func (x *Mesh) GetLayerCounts() []byte {
	if x != nil {
		return x.LayerCounts
	}
	return nil
}

func (x *Mesh) GetTexture() []*Texture {
	if x != nil {
		return x.Texture
	}
	return nil
}

func (x *Mesh) GetTextureCoordinates() []byte {
	if x != nil {
		return x.TextureCoordinates
	}
	return nil
}

func (x *Mesh) GetUvOffsetAndScale() []float32 {
	if x != nil {
		return x.UvOffsetAndScale
	}
	return nil
}

func (x *Mesh) GetLayerAndOctantCounts() []byte {
	if x != nil {
		return x.LayerAndOctantCounts
	}
	return nil
}

func (x *Mesh) GetNormals() []byte {
	if x != nil {
		return x.Normals
	}
	return nil
}

func (x *Mesh) GetNormalsDev() []byte {
	if x != nil {
		return x.NormalsDev
	}
	return nil
}

func (x *Mesh) GetMeshId() uint32 {
	if x != nil && x.MeshId != nil {
		return *x.MeshId
	}
	return 0
}

func (x *Mesh) GetSkirtFlags() []byte {
	if x != nil {
		return x.SkirtFlags
	}
	return nil
}

// Texture 定义纹理
type Texture struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Data            [][]byte               `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`                                                                                         // 纹理数据
	Format          *Texture_Format        `protobuf:"varint,2,opt,name=format,enum=GoogleEarth.RockTree.Texture_Format" json:"format,omitempty"`                                           // 纹理格式
	Width           *uint32                `protobuf:"varint,3,opt,name=width,def=256" json:"width,omitempty"`                                                                              // 宽度，默认256
	Height          *uint32                `protobuf:"varint,4,opt,name=height,def=256" json:"height,omitempty"`                                                                            // 高度，默认256
	ViewDirection   *Texture_ViewDirection `protobuf:"varint,5,opt,name=view_direction,json=viewDirection,enum=GoogleEarth.RockTree.Texture_ViewDirection" json:"view_direction,omitempty"` // 视图方向
	MeshId          *uint32                `protobuf:"varint,6,opt,name=mesh_id,json=meshId" json:"mesh_id,omitempty"`                                                                      // 网格ID
	MeasurementData *QualityMeasurements   `protobuf:"bytes,7,opt,name=measurement_data,json=measurementData" json:"measurement_data,omitempty"`                                            // 质量测量数据
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Default values for Texture fields.
const (
	Default_Texture_Width  = uint32(256)
	Default_Texture_Height = uint32(256)
)

func (x *Texture) Reset() {
	*x = Texture{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Texture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Texture) ProtoMessage() {}

func (x *Texture) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Texture.ProtoReflect.Descriptor instead.
func (*Texture) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{18}
}

func (x *Texture) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Texture) GetFormat() Texture_Format {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return Texture_JPG
}

func (x *Texture) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return Default_Texture_Width
}

func (x *Texture) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return Default_Texture_Height
}

func (x *Texture) GetViewDirection() Texture_ViewDirection {
	if x != nil && x.ViewDirection != nil {
		return *x.ViewDirection
	}
	return Texture_ANY
}

func (x *Texture) GetMeshId() uint32 {
	if x != nil && x.MeshId != nil {
		return *x.MeshId
	}
	return 0
}

func (x *Texture) GetMeasurementData() *QualityMeasurements {
	if x != nil {
		return x.MeasurementData
	}
	return nil
}

// QualityMeasurements 定义质量测量
type QualityMeasurements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Psnr          *float64               `protobuf:"fixed64,1,opt,name=psnr" json:"psnr,omitempty"` // 峰值信噪比
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityMeasurements) Reset() {
	*x = QualityMeasurements{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityMeasurements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityMeasurements) ProtoMessage() {}

func (x *QualityMeasurements) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityMeasurements.ProtoReflect.Descriptor instead.
func (*QualityMeasurements) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{19}
}

func (x *QualityMeasurements) GetPsnr() float64 {
	if x != nil && x.Psnr != nil {
		return *x.Psnr
	}
	return 0
}

// TextureData 定义纹理数据
type TextureData struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	NodeKey          *NodeKey                     `protobuf:"bytes,1,opt,name=node_key,json=nodeKey" json:"node_key,omitempty"`                                     // 节点键
	Textures         []*Texture                   `protobuf:"bytes,2,rep,name=textures" json:"textures,omitempty"`                                                  // 纹理列表
	TransformInfo    []*TextureData_TransformInfo `protobuf:"bytes,3,rep,name=transform_info,json=transformInfo" json:"transform_info,omitempty"`                   // 变换信息列表
	ProjectionOrigin []float32                    `protobuf:"fixed32,4,rep,packed,name=projection_origin,json=projectionOrigin" json:"projection_origin,omitempty"` // 投影原点
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TextureData) Reset() {
	*x = TextureData{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextureData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextureData) ProtoMessage() {}

func (x *TextureData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextureData.ProtoReflect.Descriptor instead.
func (*TextureData) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{20}
}

func (x *TextureData) GetNodeKey() *NodeKey {
	if x != nil {
		return x.NodeKey
	}
	return nil
}

func (x *TextureData) GetTextures() []*Texture {
	if x != nil {
		return x.Textures
	}
	return nil
}

func (x *TextureData) GetTransformInfo() []*TextureData_TransformInfo {
	if x != nil {
		return x.TransformInfo
	}
	return nil
}

func (x *TextureData) GetProjectionOrigin() []float32 {
	if x != nil {
		return x.ProjectionOrigin
	}
	return nil
}

// Copyrights 定义版权集合
type Copyrights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Copyrights    []*Copyright           `protobuf:"bytes,1,rep,name=copyrights" json:"copyrights,omitempty"` // 版权列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Copyrights) Reset() {
	*x = Copyrights{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Copyrights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Copyrights) ProtoMessage() {}

func (x *Copyrights) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Copyrights.ProtoReflect.Descriptor instead.
func (*Copyrights) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{21}
}

func (x *Copyrights) GetCopyrights() []*Copyright {
	if x != nil {
		return x.Copyrights
	}
	return nil
}

// Copyright 定义版权信息
type Copyright struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`                               // ID
	Text          *string                `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`                            // 文本
	TextClean     *string                `protobuf:"bytes,3,opt,name=text_clean,json=textClean" json:"text_clean,omitempty"` // 清理后的文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Copyright) Reset() {
	*x = Copyright{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Copyright) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Copyright) ProtoMessage() {}

func (x *Copyright) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Copyright.ProtoReflect.Descriptor instead.
func (*Copyright) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{22}
}

func (x *Copyright) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Copyright) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *Copyright) GetTextClean() string {
	if x != nil && x.TextClean != nil {
		return *x.TextClean
	}
	return ""
}

// PlanetoidMetadata 定义行星体元数据
type PlanetoidMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RootNodeMetadata   *NodeMetadata          `protobuf:"bytes,1,opt,name=root_node_metadata,json=rootNodeMetadata" json:"root_node_metadata,omitempty"`         // 根节点元数据
	Radius             *float32               `protobuf:"fixed32,2,opt,name=radius" json:"radius,omitempty"`                                                     // 半径
	MinTerrainAltitude *float32               `protobuf:"fixed32,3,opt,name=min_terrain_altitude,json=minTerrainAltitude" json:"min_terrain_altitude,omitempty"` // 最小地形高度
	MaxTerrainAltitude *float32               `protobuf:"fixed32,4,opt,name=max_terrain_altitude,json=maxTerrainAltitude" json:"max_terrain_altitude,omitempty"` // 最大地形高度
	MaxImageryEpoch    *uint32                `protobuf:"varint,5,opt,name=max_imagery_epoch,json=maxImageryEpoch" json:"max_imagery_epoch,omitempty"`           // 最大影像纪元
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlanetoidMetadata) Reset() {
	*x = PlanetoidMetadata{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanetoidMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanetoidMetadata) ProtoMessage() {}

func (x *PlanetoidMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanetoidMetadata.ProtoReflect.Descriptor instead.
func (*PlanetoidMetadata) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{23}
}

func (x *PlanetoidMetadata) GetRootNodeMetadata() *NodeMetadata {
	if x != nil {
		return x.RootNodeMetadata
	}
	return nil
}

func (x *PlanetoidMetadata) GetRadius() float32 {
	if x != nil && x.Radius != nil {
		return *x.Radius
	}
	return 0
}

func (x *PlanetoidMetadata) GetMinTerrainAltitude() float32 {
	if x != nil && x.MinTerrainAltitude != nil {
		return *x.MinTerrainAltitude
	}
	return 0
}

func (x *PlanetoidMetadata) GetMaxTerrainAltitude() float32 {
	if x != nil && x.MaxTerrainAltitude != nil {
		return *x.MaxTerrainAltitude
	}
	return 0
}

func (x *PlanetoidMetadata) GetMaxImageryEpoch() uint32 {
	if x != nil && x.MaxImageryEpoch != nil {
		return *x.MaxImageryEpoch
	}
	return 0
}

// TransformInfo 定义变换信息
type TextureData_TransformInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransformTable     []byte                 `protobuf:"bytes,1,opt,name=transform_table,json=transformTable" json:"transform_table,omitempty"`               // 变换表
	VertexTransformMap []byte                 `protobuf:"bytes,2,opt,name=vertex_transform_map,json=vertexTransformMap" json:"vertex_transform_map,omitempty"` // 顶点变换映射
	MeshId             *uint32                `protobuf:"varint,3,opt,name=mesh_id,json=meshId" json:"mesh_id,omitempty"`                                      // 网格ID
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TextureData_TransformInfo) Reset() {
	*x = TextureData_TransformInfo{}
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextureData_TransformInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextureData_TransformInfo) ProtoMessage() {}

func (x *TextureData_TransformInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rocktree_RockTree_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextureData_TransformInfo.ProtoReflect.Descriptor instead.
func (*TextureData_TransformInfo) Descriptor() ([]byte, []int) {
	return file_proto_rocktree_RockTree_proto_rawDescGZIP(), []int{20, 0}
}

func (x *TextureData_TransformInfo) GetTransformTable() []byte {
	if x != nil {
		return x.TransformTable
	}
	return nil
}

func (x *TextureData_TransformInfo) GetVertexTransformMap() []byte {
	if x != nil {
		return x.VertexTransformMap
	}
	return nil
}

func (x *TextureData_TransformInfo) GetMeshId() uint32 {
	if x != nil && x.MeshId != nil {
		return *x.MeshId
	}
	return 0
}

var File_proto_rocktree_RockTree_proto protoreflect.FileDescriptor

const file_proto_rocktree_RockTree_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/rocktree/RockTree.proto\x12\x14GoogleEarth.RockTree\"\x95\x01\n" +
	"\rTileKeyBounds\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12\x17\n" +
	"\amin_row\x18\x02 \x01(\rR\x06minRow\x12\x1d\n" +
	"\n" +
	"min_column\x18\x03 \x01(\rR\tminColumn\x12\x17\n" +
	"\amax_row\x18\x04 \x01(\rR\x06maxRow\x12\x1d\n" +
	"\n" +
	"max_column\x18\x05 \x01(\rR\tmaxColumn\"e\n" +
	"\rKmlCoordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x03 \x01(\x01R\baltitude\"\xa4\x04\n" +
	"\x17ViewportMetadataRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\rR\x05epoch\x12K\n" +
	"\x0ftile_key_bounds\x18\x02 \x03(\v2#.GoogleEarth.RockTree.TileKeyBoundsR\rtileKeyBounds\x12%\n" +
	"\x0eomit_ancestors\x18\x03 \x01(\bR\romitAncestors\x12\x85\x01\n" +
	"\x1bbulk_metadata_response_mode\x18\x04 \x01(\x0e2F.GoogleEarth.RockTree.ViewportMetadataRequest.BulkMetadataResponseModeR\x18bulkMetadataResponseMode\x12]\n" +
	"\x18terrain_elevation_coords\x18\x05 \x03(\v2#.GoogleEarth.RockTree.KmlCoordinateR\x16terrainElevationCoords\x12I\n" +
	" bulk_metadata_spdy_push_priority\x18\x06 \x01(\r:\x017R\x1cbulkMetadataSpdyPushPriority\"M\n" +
	"\x18BulkMetadataResponseMode\x12\b\n" +
	"\x04NONE\x10\x00\x12\r\n" +
	"\tSPDY_PUSH\x10\x01\x12\x18\n" +
	"\x14IN_VIEWPORT_METADATA\x10\x02\"\xdf\x02\n" +
	"\x10ViewportMetadata\x12V\n" +
	"\x12planetoid_metadata\x18\x01 \x01(\v2'.GoogleEarth.RockTree.PlanetoidMetadataR\x11planetoidMetadata\x12K\n" +
	"\x12bulk_metadata_keys\x18\x02 \x03(\v2\x1d.GoogleEarth.RockTree.NodeKeyR\x10bulkMetadataKeys\x12]\n" +
	"\x18terrain_elevation_coords\x18\x03 \x03(\v2#.GoogleEarth.RockTree.KmlCoordinateR\x16terrainElevationCoords\x12G\n" +
	"\rbulk_metadata\x18\x04 \x03(\v2\".GoogleEarth.RockTree.BulkMetadataR\fbulkMetadata\"O\n" +
	"\x13BulkMetadataRequest\x128\n" +
	"\bnode_key\x18\x01 \x01(\v2\x1d.GoogleEarth.RockTree.NodeKeyR\anodeKey\"\xc4\x02\n" +
	"\x0fNodeDataRequest\x128\n" +
	"\bnode_key\x18\x01 \x01(\v2\x1d.GoogleEarth.RockTree.NodeKeyR\anodeKey\x12K\n" +
	"\x0etexture_format\x18\x02 \x01(\x0e2$.GoogleEarth.RockTree.Texture.FormatR\rtextureFormat\x12#\n" +
	"\rimagery_epoch\x18\x03 \x01(\rR\fimageryEpoch\x12!\n" +
	"\fomit_texture\x18\x04 \x01(\bR\vomitTexture\x12\x12\n" +
	"\x04date\x18\x05 \x01(\x05R\x04date\x12\"\n" +
	"\fmilliseconds\x18\x06 \x01(\x05R\fmilliseconds\x12*\n" +
	"\x11texture_is_shared\x18\a \x01(\bR\x0ftextureIsShared\"3\n" +
	"\aNodeKey\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\"\xaa\x02\n" +
	"\rRockTreeTasks\x12A\n" +
	"\rhead_node_key\x18\x01 \x01(\v2\x1d.GoogleEarth.RockTree.NodeKeyR\vheadNodeKey\x12W\n" +
	"\x13node_metadata_tasks\x18\x02 \x03(\v2'.GoogleEarth.RockTree.NodeMetadataTasksR\x11nodeMetadataTasks\x122\n" +
	"\x15default_imagery_epoch\x18\x03 \x01(\rR\x13defaultImageryEpoch\x12I\n" +
	"!default_available_texture_formats\x18\x04 \x01(\rR\x1edefaultAvailableTextureFormats\"\xe0\x01\n" +
	"\x11NodeMetadataTasks\x12$\n" +
	"\x0epath_and_flags\x18\x01 \x01(\rR\fpathAndFlags\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\x12.\n" +
	"\x13bulk_metadata_epoch\x18\x03 \x01(\rR\x11bulkMetadataEpoch\x12#\n" +
	"\rimagery_epoch\x18\x04 \x01(\rR\fimageryEpoch\x12:\n" +
	"\x19available_texture_formats\x18\x05 \x01(\rR\x17availableTextureFormats\"(\n" +
	"\x10CopyrightRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\rR\x05epoch\"\x94\x02\n" +
	"\x12TextureDataRequest\x128\n" +
	"\bnode_key\x18\x01 \x01(\v2\x1d.GoogleEarth.RockTree.NodeKeyR\anodeKey\x12K\n" +
	"\x0etexture_format\x18\x02 \x01(\x0e2$.GoogleEarth.RockTree.Texture.FormatR\rtextureFormat\x12R\n" +
	"\x0eview_direction\x18\x03 \x01(\x0e2+.GoogleEarth.RockTree.Texture.ViewDirectionR\rviewDirection\x12#\n" +
	"\rimagery_epoch\x18\x04 \x01(\rR\fimageryEpoch\"\xf6\x05\n" +
	"\fBulkMetadata\x12G\n" +
	"\rnode_metadata\x18\x01 \x03(\v2\".GoogleEarth.RockTree.NodeMetadataR\fnodeMetadata\x12A\n" +
	"\rhead_node_key\x18\x02 \x01(\v2\x1d.GoogleEarth.RockTree.NodeKeyR\vheadNodeKey\x12,\n" +
	"\x10head_node_center\x18\x03 \x03(\x01B\x02\x10\x01R\x0eheadNodeCenter\x12,\n" +
	"\x10meters_per_texel\x18\x04 \x03(\x02B\x02\x10\x01R\x0emetersPerTexel\x122\n" +
	"\x15default_imagery_epoch\x18\x05 \x01(\rR\x13defaultImageryEpoch\x12I\n" +
	"!default_available_texture_formats\x18\x06 \x01(\rR\x1edefaultAvailableTextureFormats\x12X\n" +
	")default_available_view_dependent_textures\x18\a \x01(\rR%defaultAvailableViewDependentTextures\x12e\n" +
	"0default_available_view_dependent_texture_formats\x18\b \x01(\rR+defaultAvailableViewDependentTextureFormats\x12M\n" +
	"\x12common_dated_nodes\x18\t \x03(\v2\x1f.GoogleEarth.RockTree.DatedNodeR\x10commonDatedNodes\x12o\n" +
	"\x1edefault_acquisition_date_range\x18\n" +
	" \x01(\v2*.GoogleEarth.RockTree.AcquisitionDateRangeR\x1bdefaultAcquisitionDateRange\"\xa7\x06\n" +
	"\fNodeMetadata\x12$\n" +
	"\x0epath_and_flags\x18\x01 \x01(\rR\fpathAndFlags\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\x12.\n" +
	"\x13bulk_metadata_epoch\x18\x05 \x01(\rR\x11bulkMetadataEpoch\x122\n" +
	"\x15oriented_bounding_box\x18\x03 \x01(\fR\x13orientedBoundingBox\x12(\n" +
	"\x10meters_per_texel\x18\x04 \x01(\x02R\x0emetersPerTexel\x12K\n" +
	" processing_oriented_bounding_box\x18\x06 \x03(\x01B\x02\x10\x01R\x1dprocessingOrientedBoundingBox\x12#\n" +
	"\rimagery_epoch\x18\a \x01(\rR\fimageryEpoch\x12:\n" +
	"\x19available_texture_formats\x18\b \x01(\rR\x17availableTextureFormats\x12I\n" +
	"!available_view_dependent_textures\x18\t \x01(\rR\x1eavailableViewDependentTextures\x12V\n" +
	"(available_view_dependent_texture_formats\x18\n" +
	" \x01(\rR$availableViewDependentTextureFormats\x12@\n" +
	"\vdated_nodes\x18\v \x03(\v2\x1f.GoogleEarth.RockTree.DatedNodeR\n" +
	"datedNodes\x12`\n" +
	"\x16acquisition_date_range\x18\f \x01(\v2*.GoogleEarth.RockTree.AcquisitionDateRangeR\x14acquisitionDateRange\"X\n" +
	"\x05Flags\x12\x0f\n" +
	"\vRICH3D_LEAF\x10\x01\x12\x11\n" +
	"\rRICH3D_NODATA\x10\x02\x12\b\n" +
	"\x04LEAF\x10\x04\x12\n" +
	"\n" +
	"\x06NODATA\x10\b\x12\x15\n" +
	"\x11USE_IMAGERY_EPOCH\x10\x10\"\x9f\x01\n" +
	"\tDatedNode\x12\x12\n" +
	"\x04date\x18\x01 \x01(\rR\x04date\x12\"\n" +
	"\fmilliseconds\x18\x02 \x01(\rR\fmilliseconds\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x05R\x05epoch\x12!\n" +
	"\fshared_epoch\x18\x05 \x01(\x05R\vsharedEpoch\x12!\n" +
	"\fcoarse_level\x18\x04 \x01(\x05R\vcoarseLevel\"I\n" +
	"\x0fAcquisitionDate\x12\x12\n" +
	"\x04date\x18\x01 \x01(\rR\x04date\x12\"\n" +
	"\fmilliseconds\x18\x02 \x01(\rR\fmilliseconds\"\x8c\x01\n" +
	"\x14AcquisitionDateRange\x12;\n" +
	"\x05begin\x18\x01 \x01(\v2%.GoogleEarth.RockTree.AcquisitionDateR\x05begin\x127\n" +
	"\x03end\x18\x02 \x01(\v2%.GoogleEarth.RockTree.AcquisitionDateR\x03end\"\xb4\x03\n" +
	"\bNodeData\x127\n" +
	"\x16matrix_globe_from_mesh\x18\x01 \x03(\x01B\x02\x10\x01R\x13matrixGlobeFromMesh\x122\n" +
	"\x06meshes\x18\x02 \x03(\v2\x1a.GoogleEarth.RockTree.MeshR\x06meshes\x12#\n" +
	"\rcopyright_ids\x18\x03 \x03(\rR\fcopyrightIds\x128\n" +
	"\bnode_key\x18\x04 \x01(\v2\x1d.GoogleEarth.RockTree.NodeKeyR\anodeKey\x12,\n" +
	"\x10kml_bounding_box\x18\x05 \x03(\x01B\x02\x10\x01R\x0ekmlBoundingBox\x129\n" +
	"\n" +
	"water_mesh\x18\x06 \x01(\v2\x1a.GoogleEarth.RockTree.MeshR\twaterMesh\x12P\n" +
	"\x16overlay_surface_meshes\x18\a \x03(\v2\x1a.GoogleEarth.RockTree.MeshR\x14overlaySurfaceMeshes\x12!\n" +
	"\fnormal_table\x18\b \x01(\fR\vnormalTable\"\x81\a\n" +
	"\x04Mesh\x12\x1a\n" +
	"\bvertices\x18\x01 \x01(\fR\bvertices\x12#\n" +
	"\rvertex_alphas\x18\t \x01(\fR\fvertexAlphas\x12%\n" +
	"\x0etexture_coords\x18\x02 \x01(\fR\rtextureCoords\x12\x18\n" +
	"\aindices\x18\x03 \x01(\fR\aindices\x12#\n" +
	"\roctant_ranges\x18\x04 \x01(\fR\foctantRanges\x12!\n" +
	"\flayer_counts\x18\x05 \x01(\fR\vlayerCounts\x127\n" +
	"\atexture\x18\x06 \x03(\v2\x1d.GoogleEarth.RockTree.TextureR\atexture\x12/\n" +
	"\x13texture_coordinates\x18\a \x01(\fR\x12textureCoordinates\x121\n" +
	"\x13uv_offset_and_scale\x18\n" +
	" \x03(\x02B\x02\x10\x01R\x10uvOffsetAndScale\x125\n" +
	"\x17layer_and_octant_counts\x18\b \x01(\fR\x14layerAndOctantCounts\x12\x18\n" +
	"\anormals\x18\v \x01(\fR\anormals\x12\x1f\n" +
	"\vnormals_dev\x18\x10 \x01(\fR\n" +
	"normalsDev\x12\x17\n" +
	"\amesh_id\x18\f \x01(\rR\x06meshId\x12\x1f\n" +
	"\vskirt_flags\x18\r \x01(\fR\n" +
	"skirtFlags\"\xd6\x01\n" +
	"\x05Layer\x12\x0e\n" +
	"\n" +
	"OVERGROUND\x10\x00\x12\x17\n" +
	"\x13TERRAIN_BELOW_WATER\x10\x01\x12\x17\n" +
	"\x13TERRAIN_ABOVE_WATER\x10\x02\x12\x12\n" +
	"\x0eTERRAIN_HIDDEN\x10\x03\x12\t\n" +
	"\x05WATER\x10\x04\x12\x10\n" +
	"\fWATER_SKIRTS\x10\x05\x12\x19\n" +
	"\x15WATER_SKIRTS_INVERTED\x10\x06\x12\x13\n" +
	"\x0fOVERLAY_SURFACE\x10\a\x12\x1a\n" +
	"\x16OVERLAY_SURFACE_SKIRTS\x10\b\x12\x0e\n" +
	"\n" +
	"NUM_LAYERS\x10\t\"\x8c\x01\n" +
	"\tLayerMask\x12\x1b\n" +
	"\x17TERRAIN_WITH_OVERGROUND\x10\a\x12\x16\n" +
	"\x12TERRAIN_WITH_WATER\x10\x1c\x12\x19\n" +
	"\x15TERRAIN_WITHOUT_WATER\x10\x0e\x12\x18\n" +
	"\x13OVERLAY_WITH_SKIRTS\x10\x80\x03\x12\x15\n" +
	"\x11WATER_WITH_SKIRTS\x10p\"\x89\x04\n" +
	"\aTexture\x12\x12\n" +
	"\x04data\x18\x01 \x03(\fR\x04data\x12<\n" +
	"\x06format\x18\x02 \x01(\x0e2$.GoogleEarth.RockTree.Texture.FormatR\x06format\x12\x19\n" +
	"\x05width\x18\x03 \x01(\r:\x03256R\x05width\x12\x1b\n" +
	"\x06height\x18\x04 \x01(\r:\x03256R\x06height\x12R\n" +
	"\x0eview_direction\x18\x05 \x01(\x0e2+.GoogleEarth.RockTree.Texture.ViewDirectionR\rviewDirection\x12\x17\n" +
	"\amesh_id\x18\x06 \x01(\rR\x06meshId\x12T\n" +
	"\x10measurement_data\x18\a \x01(\v2).GoogleEarth.RockTree.QualityMeasurementsR\x0fmeasurementData\"V\n" +
	"\x06Format\x12\a\n" +
	"\x03JPG\x10\x01\x12\b\n" +
	"\x04DXT1\x10\x02\x12\b\n" +
	"\x04ETC1\x10\x03\x12\n" +
	"\n" +
	"\x06PVRTC2\x10\x04\x12\n" +
	"\n" +
	"\x06PVRTC4\x10\x05\x12\f\n" +
	"\bCRN_DXT1\x10\x06\x12\t\n" +
	"\x05HETC2\x10\n" +
	"\"Y\n" +
	"\rViewDirection\x12\a\n" +
	"\x03ANY\x10\x00\x12\t\n" +
	"\x05NADIR\x10\x01\x12\f\n" +
	"\bNORTH_45\x10\x02\x12\v\n" +
	"\aEAST_45\x10\x03\x12\f\n" +
	"\bSOUTH_45\x10\x04\x12\v\n" +
	"\aWEST_45\x10\x05\")\n" +
	"\x13QualityMeasurements\x12\x12\n" +
	"\x04psnr\x18\x01 \x01(\x01R\x04psnr\"\x91\x03\n" +
	"\vTextureData\x128\n" +
	"\bnode_key\x18\x01 \x01(\v2\x1d.GoogleEarth.RockTree.NodeKeyR\anodeKey\x129\n" +
	"\btextures\x18\x02 \x03(\v2\x1d.GoogleEarth.RockTree.TextureR\btextures\x12V\n" +
	"\x0etransform_info\x18\x03 \x03(\v2/.GoogleEarth.RockTree.TextureData.TransformInfoR\rtransformInfo\x12/\n" +
	"\x11projection_origin\x18\x04 \x03(\x02B\x02\x10\x01R\x10projectionOrigin\x1a\x83\x01\n" +
	"\rTransformInfo\x12'\n" +
	"\x0ftransform_table\x18\x01 \x01(\fR\x0etransformTable\x120\n" +
	"\x14vertex_transform_map\x18\x02 \x01(\fR\x12vertexTransformMap\x12\x17\n" +
	"\amesh_id\x18\x03 \x01(\rR\x06meshId\"M\n" +
	"\n" +
	"Copyrights\x12?\n" +
	"\n" +
	"copyrights\x18\x01 \x03(\v2\x1f.GoogleEarth.RockTree.CopyrightR\n" +
	"copyrights\"N\n" +
	"\tCopyright\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"text_clean\x18\x03 \x01(\tR\ttextClean\"\x8d\x02\n" +
	"\x11PlanetoidMetadata\x12P\n" +
	"\x12root_node_metadata\x18\x01 \x01(\v2\".GoogleEarth.RockTree.NodeMetadataR\x10rootNodeMetadata\x12\x16\n" +
	"\x06radius\x18\x02 \x01(\x02R\x06radius\x120\n" +
	"\x14min_terrain_altitude\x18\x03 \x01(\x02R\x12minTerrainAltitude\x120\n" +
	"\x14max_terrain_altitude\x18\x04 \x01(\x02R\x12maxTerrainAltitude\x12*\n" +
	"\x11max_imagery_epoch\x18\x05 \x01(\rR\x0fmaxImageryEpochB\x1cZ\x1autls_client/proto/rocktree"

var (
	file_proto_rocktree_RockTree_proto_rawDescOnce sync.Once
	file_proto_rocktree_RockTree_proto_rawDescData []byte
)

func file_proto_rocktree_RockTree_proto_rawDescGZIP() []byte {
	file_proto_rocktree_RockTree_proto_rawDescOnce.Do(func() {
		file_proto_rocktree_RockTree_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rocktree_RockTree_proto_rawDesc), len(file_proto_rocktree_RockTree_proto_rawDesc)))
	})
	return file_proto_rocktree_RockTree_proto_rawDescData
}

var file_proto_rocktree_RockTree_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_rocktree_RockTree_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_rocktree_RockTree_proto_goTypes = []any{
	(ViewportMetadataRequest_BulkMetadataResponseMode)(0), // 0: GoogleEarth.RockTree.ViewportMetadataRequest.BulkMetadataResponseMode
	(NodeMetadata_Flags)(0),                               // 1: GoogleEarth.RockTree.NodeMetadata.Flags
	(Mesh_Layer)(0),                                       // 2: GoogleEarth.RockTree.Mesh.Layer
	(Mesh_LayerMask)(0),                                   // 3: GoogleEarth.RockTree.Mesh.LayerMask
	(Texture_Format)(0),                                   // 4: GoogleEarth.RockTree.Texture.Format
	(Texture_ViewDirection)(0),                            // 5: GoogleEarth.RockTree.Texture.ViewDirection
	(*TileKeyBounds)(nil),                                 // 6: GoogleEarth.RockTree.TileKeyBounds
	(*KmlCoordinate)(nil),                                 // 7: GoogleEarth.RockTree.KmlCoordinate
	(*ViewportMetadataRequest)(nil),                       // 8: GoogleEarth.RockTree.ViewportMetadataRequest
	(*ViewportMetadata)(nil),                              // 9: GoogleEarth.RockTree.ViewportMetadata
	(*BulkMetadataRequest)(nil),                           // 10: GoogleEarth.RockTree.BulkMetadataRequest
	(*NodeDataRequest)(nil),                               // 11: GoogleEarth.RockTree.NodeDataRequest
	(*NodeKey)(nil),                                       // 12: GoogleEarth.RockTree.NodeKey
	(*RockTreeTasks)(nil),                                 // 13: GoogleEarth.RockTree.RockTreeTasks
	(*NodeMetadataTasks)(nil),                             // 14: GoogleEarth.RockTree.NodeMetadataTasks
	(*CopyrightRequest)(nil),                              // 15: GoogleEarth.RockTree.CopyrightRequest
	(*TextureDataRequest)(nil),                            // 16: GoogleEarth.RockTree.TextureDataRequest
	(*BulkMetadata)(nil),                                  // 17: GoogleEarth.RockTree.BulkMetadata
	(*NodeMetadata)(nil),                                  // 18: GoogleEarth.RockTree.NodeMetadata
	(*DatedNode)(nil),                                     // 19: GoogleEarth.RockTree.DatedNode
	(*AcquisitionDate)(nil),                               // 20: GoogleEarth.RockTree.AcquisitionDate
	(*AcquisitionDateRange)(nil),                          // 21: GoogleEarth.RockTree.AcquisitionDateRange
	(*NodeData)(nil),                                      // 22: GoogleEarth.RockTree.NodeData
	(*Mesh)(nil),                                          // 23: GoogleEarth.RockTree.Mesh
	(*Texture)(nil),                                       // 24: GoogleEarth.RockTree.Texture
	(*QualityMeasurements)(nil),                           // 25: GoogleEarth.RockTree.QualityMeasurements
	(*TextureData)(nil),                                   // 26: GoogleEarth.RockTree.TextureData
	(*Copyrights)(nil),                                    // 27: GoogleEarth.RockTree.Copyrights
	(*Copyright)(nil),                                     // 28: GoogleEarth.RockTree.Copyright
	(*PlanetoidMetadata)(nil),                             // 29: GoogleEarth.RockTree.PlanetoidMetadata
	(*TextureData_TransformInfo)(nil),                     // 30: GoogleEarth.RockTree.TextureData.TransformInfo
}
var file_proto_rocktree_RockTree_proto_depIdxs = []int32{
	6,  // 0: GoogleEarth.RockTree.ViewportMetadataRequest.tile_key_bounds:type_name -> GoogleEarth.RockTree.TileKeyBounds
	0,  // 1: GoogleEarth.RockTree.ViewportMetadataRequest.bulk_metadata_response_mode:type_name -> GoogleEarth.RockTree.ViewportMetadataRequest.BulkMetadataResponseMode
	7,  // 2: GoogleEarth.RockTree.ViewportMetadataRequest.terrain_elevation_coords:type_name -> GoogleEarth.RockTree.KmlCoordinate
	29, // 3: GoogleEarth.RockTree.ViewportMetadata.planetoid_metadata:type_name -> GoogleEarth.RockTree.PlanetoidMetadata
	12, // 4: GoogleEarth.RockTree.ViewportMetadata.bulk_metadata_keys:type_name -> GoogleEarth.RockTree.NodeKey
	7,  // 5: GoogleEarth.RockTree.ViewportMetadata.terrain_elevation_coords:type_name -> GoogleEarth.RockTree.KmlCoordinate
	17, // 6: GoogleEarth.RockTree.ViewportMetadata.bulk_metadata:type_name -> GoogleEarth.RockTree.BulkMetadata
	12, // 7: GoogleEarth.RockTree.BulkMetadataRequest.node_key:type_name -> GoogleEarth.RockTree.NodeKey
	12, // 8: GoogleEarth.RockTree.NodeDataRequest.node_key:type_name -> GoogleEarth.RockTree.NodeKey
	4,  // 9: GoogleEarth.RockTree.NodeDataRequest.texture_format:type_name -> GoogleEarth.RockTree.Texture.Format
	12, // 10: GoogleEarth.RockTree.RockTreeTasks.head_node_key:type_name -> GoogleEarth.RockTree.NodeKey
	14, // 11: GoogleEarth.RockTree.RockTreeTasks.node_metadata_tasks:type_name -> GoogleEarth.RockTree.NodeMetadataTasks
	12, // 12: GoogleEarth.RockTree.TextureDataRequest.node_key:type_name -> GoogleEarth.RockTree.NodeKey
	4,  // 13: GoogleEarth.RockTree.TextureDataRequest.texture_format:type_name -> GoogleEarth.RockTree.Texture.Format
	5,  // 14: GoogleEarth.RockTree.TextureDataRequest.view_direction:type_name -> GoogleEarth.RockTree.Texture.ViewDirection
	18, // 15: GoogleEarth.RockTree.BulkMetadata.node_metadata:type_name -> GoogleEarth.RockTree.NodeMetadata
	12, // 16: GoogleEarth.RockTree.BulkMetadata.head_node_key:type_name -> GoogleEarth.RockTree.NodeKey
	19, // 17: GoogleEarth.RockTree.BulkMetadata.common_dated_nodes:type_name -> GoogleEarth.RockTree.DatedNode
	21, // 18: GoogleEarth.RockTree.BulkMetadata.default_acquisition_date_range:type_name -> GoogleEarth.RockTree.AcquisitionDateRange
	19, // 19: GoogleEarth.RockTree.NodeMetadata.dated_nodes:type_name -> GoogleEarth.RockTree.DatedNode
	21, // 20: GoogleEarth.RockTree.NodeMetadata.acquisition_date_range:type_name -> GoogleEarth.RockTree.AcquisitionDateRange
	20, // 21: GoogleEarth.RockTree.AcquisitionDateRange.begin:type_name -> GoogleEarth.RockTree.AcquisitionDate
	20, // 22: GoogleEarth.RockTree.AcquisitionDateRange.end:type_name -> GoogleEarth.RockTree.AcquisitionDate
	23, // 23: GoogleEarth.RockTree.NodeData.meshes:type_name -> GoogleEarth.RockTree.Mesh
	12, // 24: GoogleEarth.RockTree.NodeData.node_key:type_name -> GoogleEarth.RockTree.NodeKey
	23, // 25: GoogleEarth.RockTree.NodeData.water_mesh:type_name -> GoogleEarth.RockTree.Mesh
	23, // 26: GoogleEarth.RockTree.NodeData.overlay_surface_meshes:type_name -> GoogleEarth.RockTree.Mesh
	24, // 27: GoogleEarth.RockTree.Mesh.texture:type_name -> GoogleEarth.RockTree.Texture
	4,  // 28: GoogleEarth.RockTree.Texture.format:type_name -> GoogleEarth.RockTree.Texture.Format
	5,  // 29: GoogleEarth.RockTree.Texture.view_direction:type_name -> GoogleEarth.RockTree.Texture.ViewDirection
	25, // 30: GoogleEarth.RockTree.Texture.measurement_data:type_name -> GoogleEarth.RockTree.QualityMeasurements
	12, // 31: GoogleEarth.RockTree.TextureData.node_key:type_name -> GoogleEarth.RockTree.NodeKey
	24, // 32: GoogleEarth.RockTree.TextureData.textures:type_name -> GoogleEarth.RockTree.Texture
	30, // 33: GoogleEarth.RockTree.TextureData.transform_info:type_name -> GoogleEarth.RockTree.TextureData.TransformInfo
	28, // 34: GoogleEarth.RockTree.Copyrights.copyrights:type_name -> GoogleEarth.RockTree.Copyright
	18, // 35: GoogleEarth.RockTree.PlanetoidMetadata.root_node_metadata:type_name -> GoogleEarth.RockTree.NodeMetadata
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_proto_rocktree_RockTree_proto_init() }
func file_proto_rocktree_RockTree_proto_init() {
	if File_proto_rocktree_RockTree_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rocktree_RockTree_proto_rawDesc), len(file_proto_rocktree_RockTree_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rocktree_RockTree_proto_goTypes,
		DependencyIndexes: file_proto_rocktree_RockTree_proto_depIdxs,
		EnumInfos:         file_proto_rocktree_RockTree_proto_enumTypes,
		MessageInfos:      file_proto_rocktree_RockTree_proto_msgTypes,
	}.Build()
	File_proto_rocktree_RockTree_proto = out.File
	file_proto_rocktree_RockTree_proto_goTypes = nil
	file_proto_rocktree_RockTree_proto_depIdxs = nil
}
