// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ippool.proto

package ippool

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IPPoolService_GetAllHosts_FullMethodName            = "/ippool.IPPoolService/GetAllHosts"
	IPPoolService_GetHostInfo_FullMethodName            = "/ippool.IPPoolService/GetHostInfo"
	IPPoolService_GetIPPool_FullMethodName              = "/ippool.IPPoolService/GetIPPool"
	IPPoolService_GetDetailIPPool_FullMethodName        = "/ippool.IPPoolService/GetDetailIPPool"
	IPPoolService_GetIPDetail_FullMethodName            = "/ippool.IPPoolService/GetIPDetail"
	IPPoolService_SearchIPs_FullMethodName              = "/ippool.IPPoolService/SearchIPs"
	IPPoolService_GetRandomIP_FullMethodName            = "/ippool.IPPoolService/GetRandomIP"
	IPPoolService_GetAllIPsByHost_FullMethodName        = "/ippool.IPPoolService/GetAllIPsByHost"
	IPPoolService_AnalyzeAll_FullMethodName             = "/ippool.IPPoolService/AnalyzeAll"
	IPPoolService_AnalyzeByHost_FullMethodName          = "/ippool.IPPoolService/AnalyzeByHost"
	IPPoolService_AnalyzeByCountry_FullMethodName       = "/ippool.IPPoolService/AnalyzeByCountry"
	IPPoolService_AnalyzeByCity_FullMethodName          = "/ippool.IPPoolService/AnalyzeByCity"
	IPPoolService_AnalyzeByISP_FullMethodName           = "/ippool.IPPoolService/AnalyzeByISP"
	IPPoolService_AnalyzeByDataCenter_FullMethodName    = "/ippool.IPPoolService/AnalyzeByDataCenter"
	IPPoolService_GetCountriesList_FullMethodName       = "/ippool.IPPoolService/GetCountriesList"
	IPPoolService_GetCitiesByCountry_FullMethodName     = "/ippool.IPPoolService/GetCitiesByCountry"
	IPPoolService_GetIPsByCountryAndCity_FullMethodName = "/ippool.IPPoolService/GetIPsByCountryAndCity"
	IPPoolService_SyncAll_FullMethodName                = "/ippool.IPPoolService/SyncAll"
	IPPoolService_SyncHosts_FullMethodName              = "/ippool.IPPoolService/SyncHosts"
	IPPoolService_SyncIPPool_FullMethodName             = "/ippool.IPPoolService/SyncIPPool"
	IPPoolService_SyncDetailIPPool_FullMethodName       = "/ippool.IPPoolService/SyncDetailIPPool"
	IPPoolService_GetServiceStatus_FullMethodName       = "/ippool.IPPoolService/GetServiceStatus"
)

// IPPoolServiceClient is the client API for IPPoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IP 池服务
type IPPoolServiceClient interface {
	// 获取所有主机列表
	GetAllHosts(ctx context.Context, in *GetAllHostsRequest, opts ...grpc.CallOption) (*GetAllHostsResponse, error)
	// 获取指定主机信息
	GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error)
	// 获取简化格式 IP 池数据
	GetIPPool(ctx context.Context, in *GetIPPoolRequest, opts ...grpc.CallOption) (*GetIPPoolResponse, error)
	// 获取详细格式 IP 池数据
	GetDetailIPPool(ctx context.Context, in *GetDetailIPPoolRequest, opts ...grpc.CallOption) (*GetDetailIPPoolResponse, error)
	// 获取指定 IP 的详细信息
	GetIPDetail(ctx context.Context, in *GetIPDetailRequest, opts ...grpc.CallOption) (*GetIPDetailResponse, error)
	// 搜索 IP（支持多条件）
	SearchIPs(ctx context.Context, in *SearchIPsRequest, opts ...grpc.CallOption) (*SearchIPsResponse, error)
	// 获取随机 IP
	GetRandomIP(ctx context.Context, in *GetRandomIPRequest, opts ...grpc.CallOption) (*GetRandomIPResponse, error)
	// 获取指定主机的所有 IP
	GetAllIPsByHost(ctx context.Context, in *GetAllIPsByHostRequest, opts ...grpc.CallOption) (*GetAllIPsByHostResponse, error)
	// 分析所有数据
	AnalyzeAll(ctx context.Context, in *AnalyzeAllRequest, opts ...grpc.CallOption) (*AnalyzeAllResponse, error)
	// 分析指定主机
	AnalyzeByHost(ctx context.Context, in *AnalyzeByHostRequest, opts ...grpc.CallOption) (*AnalyzeByHostResponse, error)
	// 按国家分析
	AnalyzeByCountry(ctx context.Context, in *AnalyzeByCountryRequest, opts ...grpc.CallOption) (*AnalyzeByCountryResponse, error)
	// 按城市分析
	AnalyzeByCity(ctx context.Context, in *AnalyzeByCityRequest, opts ...grpc.CallOption) (*AnalyzeByCityResponse, error)
	// 按 ISP 分析
	AnalyzeByISP(ctx context.Context, in *AnalyzeByISPRequest, opts ...grpc.CallOption) (*AnalyzeByISPResponse, error)
	// 按数据中心分析
	AnalyzeByDataCenter(ctx context.Context, in *AnalyzeByDataCenterRequest, opts ...grpc.CallOption) (*AnalyzeByDataCenterResponse, error)
	// 按国家和城市分组查询
	GetCountriesList(ctx context.Context, in *GetCountriesListRequest, opts ...grpc.CallOption) (*GetCountriesListResponse, error)
	GetCitiesByCountry(ctx context.Context, in *GetCitiesByCountryRequest, opts ...grpc.CallOption) (*GetCitiesByCountryResponse, error)
	GetIPsByCountryAndCity(ctx context.Context, in *GetIPsByCountryAndCityRequest, opts ...grpc.CallOption) (*GetIPsByCountryAndCityResponse, error)
	// 同步操作
	SyncAll(ctx context.Context, in *SyncAllRequest, opts ...grpc.CallOption) (*SyncAllResponse, error)
	SyncHosts(ctx context.Context, in *SyncHostsRequest, opts ...grpc.CallOption) (*SyncHostsResponse, error)
	SyncIPPool(ctx context.Context, in *SyncIPPoolRequest, opts ...grpc.CallOption) (*SyncIPPoolResponse, error)
	SyncDetailIPPool(ctx context.Context, in *SyncDetailIPPoolRequest, opts ...grpc.CallOption) (*SyncDetailIPPoolResponse, error)
	// 获取服务状态
	GetServiceStatus(ctx context.Context, in *GetServiceStatusRequest, opts ...grpc.CallOption) (*GetServiceStatusResponse, error)
}

type iPPoolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIPPoolServiceClient(cc grpc.ClientConnInterface) IPPoolServiceClient {
	return &iPPoolServiceClient{cc}
}

func (c *iPPoolServiceClient) GetAllHosts(ctx context.Context, in *GetAllHostsRequest, opts ...grpc.CallOption) (*GetAllHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllHostsResponse)
	err := c.cc.Invoke(ctx, IPPoolService_GetAllHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostInfoResponse)
	err := c.cc.Invoke(ctx, IPPoolService_GetHostInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) GetIPPool(ctx context.Context, in *GetIPPoolRequest, opts ...grpc.CallOption) (*GetIPPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIPPoolResponse)
	err := c.cc.Invoke(ctx, IPPoolService_GetIPPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) GetDetailIPPool(ctx context.Context, in *GetDetailIPPoolRequest, opts ...grpc.CallOption) (*GetDetailIPPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDetailIPPoolResponse)
	err := c.cc.Invoke(ctx, IPPoolService_GetDetailIPPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) GetIPDetail(ctx context.Context, in *GetIPDetailRequest, opts ...grpc.CallOption) (*GetIPDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIPDetailResponse)
	err := c.cc.Invoke(ctx, IPPoolService_GetIPDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) SearchIPs(ctx context.Context, in *SearchIPsRequest, opts ...grpc.CallOption) (*SearchIPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchIPsResponse)
	err := c.cc.Invoke(ctx, IPPoolService_SearchIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) GetRandomIP(ctx context.Context, in *GetRandomIPRequest, opts ...grpc.CallOption) (*GetRandomIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRandomIPResponse)
	err := c.cc.Invoke(ctx, IPPoolService_GetRandomIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) GetAllIPsByHost(ctx context.Context, in *GetAllIPsByHostRequest, opts ...grpc.CallOption) (*GetAllIPsByHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllIPsByHostResponse)
	err := c.cc.Invoke(ctx, IPPoolService_GetAllIPsByHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) AnalyzeAll(ctx context.Context, in *AnalyzeAllRequest, opts ...grpc.CallOption) (*AnalyzeAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeAllResponse)
	err := c.cc.Invoke(ctx, IPPoolService_AnalyzeAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) AnalyzeByHost(ctx context.Context, in *AnalyzeByHostRequest, opts ...grpc.CallOption) (*AnalyzeByHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeByHostResponse)
	err := c.cc.Invoke(ctx, IPPoolService_AnalyzeByHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) AnalyzeByCountry(ctx context.Context, in *AnalyzeByCountryRequest, opts ...grpc.CallOption) (*AnalyzeByCountryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeByCountryResponse)
	err := c.cc.Invoke(ctx, IPPoolService_AnalyzeByCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) AnalyzeByCity(ctx context.Context, in *AnalyzeByCityRequest, opts ...grpc.CallOption) (*AnalyzeByCityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeByCityResponse)
	err := c.cc.Invoke(ctx, IPPoolService_AnalyzeByCity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) AnalyzeByISP(ctx context.Context, in *AnalyzeByISPRequest, opts ...grpc.CallOption) (*AnalyzeByISPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeByISPResponse)
	err := c.cc.Invoke(ctx, IPPoolService_AnalyzeByISP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) AnalyzeByDataCenter(ctx context.Context, in *AnalyzeByDataCenterRequest, opts ...grpc.CallOption) (*AnalyzeByDataCenterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeByDataCenterResponse)
	err := c.cc.Invoke(ctx, IPPoolService_AnalyzeByDataCenter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) GetCountriesList(ctx context.Context, in *GetCountriesListRequest, opts ...grpc.CallOption) (*GetCountriesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCountriesListResponse)
	err := c.cc.Invoke(ctx, IPPoolService_GetCountriesList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) GetCitiesByCountry(ctx context.Context, in *GetCitiesByCountryRequest, opts ...grpc.CallOption) (*GetCitiesByCountryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCitiesByCountryResponse)
	err := c.cc.Invoke(ctx, IPPoolService_GetCitiesByCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) GetIPsByCountryAndCity(ctx context.Context, in *GetIPsByCountryAndCityRequest, opts ...grpc.CallOption) (*GetIPsByCountryAndCityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIPsByCountryAndCityResponse)
	err := c.cc.Invoke(ctx, IPPoolService_GetIPsByCountryAndCity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) SyncAll(ctx context.Context, in *SyncAllRequest, opts ...grpc.CallOption) (*SyncAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncAllResponse)
	err := c.cc.Invoke(ctx, IPPoolService_SyncAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) SyncHosts(ctx context.Context, in *SyncHostsRequest, opts ...grpc.CallOption) (*SyncHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncHostsResponse)
	err := c.cc.Invoke(ctx, IPPoolService_SyncHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) SyncIPPool(ctx context.Context, in *SyncIPPoolRequest, opts ...grpc.CallOption) (*SyncIPPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncIPPoolResponse)
	err := c.cc.Invoke(ctx, IPPoolService_SyncIPPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) SyncDetailIPPool(ctx context.Context, in *SyncDetailIPPoolRequest, opts ...grpc.CallOption) (*SyncDetailIPPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDetailIPPoolResponse)
	err := c.cc.Invoke(ctx, IPPoolService_SyncDetailIPPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPPoolServiceClient) GetServiceStatus(ctx context.Context, in *GetServiceStatusRequest, opts ...grpc.CallOption) (*GetServiceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceStatusResponse)
	err := c.cc.Invoke(ctx, IPPoolService_GetServiceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IPPoolServiceServer is the server API for IPPoolService service.
// All implementations must embed UnimplementedIPPoolServiceServer
// for forward compatibility.
//
// IP 池服务
type IPPoolServiceServer interface {
	// 获取所有主机列表
	GetAllHosts(context.Context, *GetAllHostsRequest) (*GetAllHostsResponse, error)
	// 获取指定主机信息
	GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error)
	// 获取简化格式 IP 池数据
	GetIPPool(context.Context, *GetIPPoolRequest) (*GetIPPoolResponse, error)
	// 获取详细格式 IP 池数据
	GetDetailIPPool(context.Context, *GetDetailIPPoolRequest) (*GetDetailIPPoolResponse, error)
	// 获取指定 IP 的详细信息
	GetIPDetail(context.Context, *GetIPDetailRequest) (*GetIPDetailResponse, error)
	// 搜索 IP（支持多条件）
	SearchIPs(context.Context, *SearchIPsRequest) (*SearchIPsResponse, error)
	// 获取随机 IP
	GetRandomIP(context.Context, *GetRandomIPRequest) (*GetRandomIPResponse, error)
	// 获取指定主机的所有 IP
	GetAllIPsByHost(context.Context, *GetAllIPsByHostRequest) (*GetAllIPsByHostResponse, error)
	// 分析所有数据
	AnalyzeAll(context.Context, *AnalyzeAllRequest) (*AnalyzeAllResponse, error)
	// 分析指定主机
	AnalyzeByHost(context.Context, *AnalyzeByHostRequest) (*AnalyzeByHostResponse, error)
	// 按国家分析
	AnalyzeByCountry(context.Context, *AnalyzeByCountryRequest) (*AnalyzeByCountryResponse, error)
	// 按城市分析
	AnalyzeByCity(context.Context, *AnalyzeByCityRequest) (*AnalyzeByCityResponse, error)
	// 按 ISP 分析
	AnalyzeByISP(context.Context, *AnalyzeByISPRequest) (*AnalyzeByISPResponse, error)
	// 按数据中心分析
	AnalyzeByDataCenter(context.Context, *AnalyzeByDataCenterRequest) (*AnalyzeByDataCenterResponse, error)
	// 按国家和城市分组查询
	GetCountriesList(context.Context, *GetCountriesListRequest) (*GetCountriesListResponse, error)
	GetCitiesByCountry(context.Context, *GetCitiesByCountryRequest) (*GetCitiesByCountryResponse, error)
	GetIPsByCountryAndCity(context.Context, *GetIPsByCountryAndCityRequest) (*GetIPsByCountryAndCityResponse, error)
	// 同步操作
	SyncAll(context.Context, *SyncAllRequest) (*SyncAllResponse, error)
	SyncHosts(context.Context, *SyncHostsRequest) (*SyncHostsResponse, error)
	SyncIPPool(context.Context, *SyncIPPoolRequest) (*SyncIPPoolResponse, error)
	SyncDetailIPPool(context.Context, *SyncDetailIPPoolRequest) (*SyncDetailIPPoolResponse, error)
	// 获取服务状态
	GetServiceStatus(context.Context, *GetServiceStatusRequest) (*GetServiceStatusResponse, error)
	mustEmbedUnimplementedIPPoolServiceServer()
}

// UnimplementedIPPoolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIPPoolServiceServer struct{}

func (UnimplementedIPPoolServiceServer) GetAllHosts(context.Context, *GetAllHostsRequest) (*GetAllHostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllHosts not implemented")
}
func (UnimplementedIPPoolServiceServer) GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostInfo not implemented")
}
func (UnimplementedIPPoolServiceServer) GetIPPool(context.Context, *GetIPPoolRequest) (*GetIPPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIPPool not implemented")
}
func (UnimplementedIPPoolServiceServer) GetDetailIPPool(context.Context, *GetDetailIPPoolRequest) (*GetDetailIPPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetailIPPool not implemented")
}
func (UnimplementedIPPoolServiceServer) GetIPDetail(context.Context, *GetIPDetailRequest) (*GetIPDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIPDetail not implemented")
}
func (UnimplementedIPPoolServiceServer) SearchIPs(context.Context, *SearchIPsRequest) (*SearchIPsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchIPs not implemented")
}
func (UnimplementedIPPoolServiceServer) GetRandomIP(context.Context, *GetRandomIPRequest) (*GetRandomIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomIP not implemented")
}
func (UnimplementedIPPoolServiceServer) GetAllIPsByHost(context.Context, *GetAllIPsByHostRequest) (*GetAllIPsByHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllIPsByHost not implemented")
}
func (UnimplementedIPPoolServiceServer) AnalyzeAll(context.Context, *AnalyzeAllRequest) (*AnalyzeAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeAll not implemented")
}
func (UnimplementedIPPoolServiceServer) AnalyzeByHost(context.Context, *AnalyzeByHostRequest) (*AnalyzeByHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeByHost not implemented")
}
func (UnimplementedIPPoolServiceServer) AnalyzeByCountry(context.Context, *AnalyzeByCountryRequest) (*AnalyzeByCountryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeByCountry not implemented")
}
func (UnimplementedIPPoolServiceServer) AnalyzeByCity(context.Context, *AnalyzeByCityRequest) (*AnalyzeByCityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeByCity not implemented")
}
func (UnimplementedIPPoolServiceServer) AnalyzeByISP(context.Context, *AnalyzeByISPRequest) (*AnalyzeByISPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeByISP not implemented")
}
func (UnimplementedIPPoolServiceServer) AnalyzeByDataCenter(context.Context, *AnalyzeByDataCenterRequest) (*AnalyzeByDataCenterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeByDataCenter not implemented")
}
func (UnimplementedIPPoolServiceServer) GetCountriesList(context.Context, *GetCountriesListRequest) (*GetCountriesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountriesList not implemented")
}
func (UnimplementedIPPoolServiceServer) GetCitiesByCountry(context.Context, *GetCitiesByCountryRequest) (*GetCitiesByCountryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCitiesByCountry not implemented")
}
func (UnimplementedIPPoolServiceServer) GetIPsByCountryAndCity(context.Context, *GetIPsByCountryAndCityRequest) (*GetIPsByCountryAndCityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIPsByCountryAndCity not implemented")
}
func (UnimplementedIPPoolServiceServer) SyncAll(context.Context, *SyncAllRequest) (*SyncAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncAll not implemented")
}
func (UnimplementedIPPoolServiceServer) SyncHosts(context.Context, *SyncHostsRequest) (*SyncHostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncHosts not implemented")
}
func (UnimplementedIPPoolServiceServer) SyncIPPool(context.Context, *SyncIPPoolRequest) (*SyncIPPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncIPPool not implemented")
}
func (UnimplementedIPPoolServiceServer) SyncDetailIPPool(context.Context, *SyncDetailIPPoolRequest) (*SyncDetailIPPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncDetailIPPool not implemented")
}
func (UnimplementedIPPoolServiceServer) GetServiceStatus(context.Context, *GetServiceStatusRequest) (*GetServiceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceStatus not implemented")
}
func (UnimplementedIPPoolServiceServer) mustEmbedUnimplementedIPPoolServiceServer() {}
func (UnimplementedIPPoolServiceServer) testEmbeddedByValue()                       {}

// UnsafeIPPoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IPPoolServiceServer will
// result in compilation errors.
type UnsafeIPPoolServiceServer interface {
	mustEmbedUnimplementedIPPoolServiceServer()
}

func RegisterIPPoolServiceServer(s grpc.ServiceRegistrar, srv IPPoolServiceServer) {
	// If the following call pancis, it indicates UnimplementedIPPoolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IPPoolService_ServiceDesc, srv)
}

func _IPPoolService_GetAllHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).GetAllHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_GetAllHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).GetAllHosts(ctx, req.(*GetAllHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_GetHostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).GetHostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_GetHostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).GetHostInfo(ctx, req.(*GetHostInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_GetIPPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).GetIPPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_GetIPPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).GetIPPool(ctx, req.(*GetIPPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_GetDetailIPPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailIPPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).GetDetailIPPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_GetDetailIPPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).GetDetailIPPool(ctx, req.(*GetDetailIPPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_GetIPDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).GetIPDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_GetIPDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).GetIPDetail(ctx, req.(*GetIPDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_SearchIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchIPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).SearchIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_SearchIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).SearchIPs(ctx, req.(*SearchIPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_GetRandomIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).GetRandomIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_GetRandomIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).GetRandomIP(ctx, req.(*GetRandomIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_GetAllIPsByHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllIPsByHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).GetAllIPsByHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_GetAllIPsByHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).GetAllIPsByHost(ctx, req.(*GetAllIPsByHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_AnalyzeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).AnalyzeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_AnalyzeAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).AnalyzeAll(ctx, req.(*AnalyzeAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_AnalyzeByHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeByHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).AnalyzeByHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_AnalyzeByHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).AnalyzeByHost(ctx, req.(*AnalyzeByHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_AnalyzeByCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeByCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).AnalyzeByCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_AnalyzeByCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).AnalyzeByCountry(ctx, req.(*AnalyzeByCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_AnalyzeByCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeByCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).AnalyzeByCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_AnalyzeByCity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).AnalyzeByCity(ctx, req.(*AnalyzeByCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_AnalyzeByISP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeByISPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).AnalyzeByISP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_AnalyzeByISP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).AnalyzeByISP(ctx, req.(*AnalyzeByISPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_AnalyzeByDataCenter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeByDataCenterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).AnalyzeByDataCenter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_AnalyzeByDataCenter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).AnalyzeByDataCenter(ctx, req.(*AnalyzeByDataCenterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_GetCountriesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountriesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).GetCountriesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_GetCountriesList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).GetCountriesList(ctx, req.(*GetCountriesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_GetCitiesByCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCitiesByCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).GetCitiesByCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_GetCitiesByCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).GetCitiesByCountry(ctx, req.(*GetCitiesByCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_GetIPsByCountryAndCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPsByCountryAndCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).GetIPsByCountryAndCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_GetIPsByCountryAndCity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).GetIPsByCountryAndCity(ctx, req.(*GetIPsByCountryAndCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_SyncAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).SyncAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_SyncAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).SyncAll(ctx, req.(*SyncAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_SyncHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).SyncHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_SyncHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).SyncHosts(ctx, req.(*SyncHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_SyncIPPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncIPPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).SyncIPPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_SyncIPPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).SyncIPPool(ctx, req.(*SyncIPPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_SyncDetailIPPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDetailIPPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).SyncDetailIPPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_SyncDetailIPPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).SyncDetailIPPool(ctx, req.(*SyncDetailIPPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPPoolService_GetServiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPPoolServiceServer).GetServiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPPoolService_GetServiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPPoolServiceServer).GetServiceStatus(ctx, req.(*GetServiceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IPPoolService_ServiceDesc is the grpc.ServiceDesc for IPPoolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IPPoolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ippool.IPPoolService",
	HandlerType: (*IPPoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllHosts",
			Handler:    _IPPoolService_GetAllHosts_Handler,
		},
		{
			MethodName: "GetHostInfo",
			Handler:    _IPPoolService_GetHostInfo_Handler,
		},
		{
			MethodName: "GetIPPool",
			Handler:    _IPPoolService_GetIPPool_Handler,
		},
		{
			MethodName: "GetDetailIPPool",
			Handler:    _IPPoolService_GetDetailIPPool_Handler,
		},
		{
			MethodName: "GetIPDetail",
			Handler:    _IPPoolService_GetIPDetail_Handler,
		},
		{
			MethodName: "SearchIPs",
			Handler:    _IPPoolService_SearchIPs_Handler,
		},
		{
			MethodName: "GetRandomIP",
			Handler:    _IPPoolService_GetRandomIP_Handler,
		},
		{
			MethodName: "GetAllIPsByHost",
			Handler:    _IPPoolService_GetAllIPsByHost_Handler,
		},
		{
			MethodName: "AnalyzeAll",
			Handler:    _IPPoolService_AnalyzeAll_Handler,
		},
		{
			MethodName: "AnalyzeByHost",
			Handler:    _IPPoolService_AnalyzeByHost_Handler,
		},
		{
			MethodName: "AnalyzeByCountry",
			Handler:    _IPPoolService_AnalyzeByCountry_Handler,
		},
		{
			MethodName: "AnalyzeByCity",
			Handler:    _IPPoolService_AnalyzeByCity_Handler,
		},
		{
			MethodName: "AnalyzeByISP",
			Handler:    _IPPoolService_AnalyzeByISP_Handler,
		},
		{
			MethodName: "AnalyzeByDataCenter",
			Handler:    _IPPoolService_AnalyzeByDataCenter_Handler,
		},
		{
			MethodName: "GetCountriesList",
			Handler:    _IPPoolService_GetCountriesList_Handler,
		},
		{
			MethodName: "GetCitiesByCountry",
			Handler:    _IPPoolService_GetCitiesByCountry_Handler,
		},
		{
			MethodName: "GetIPsByCountryAndCity",
			Handler:    _IPPoolService_GetIPsByCountryAndCity_Handler,
		},
		{
			MethodName: "SyncAll",
			Handler:    _IPPoolService_SyncAll_Handler,
		},
		{
			MethodName: "SyncHosts",
			Handler:    _IPPoolService_SyncHosts_Handler,
		},
		{
			MethodName: "SyncIPPool",
			Handler:    _IPPoolService_SyncIPPool_Handler,
		},
		{
			MethodName: "SyncDetailIPPool",
			Handler:    _IPPoolService_SyncDetailIPPool_Handler,
		},
		{
			MethodName: "GetServiceStatus",
			Handler:    _IPPoolService_GetServiceStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ippool.proto",
}
