// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ippool.proto

package ippool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 主机信息
type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`                                      // 主机名
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`              // 简化格式文件名
	DetailFile    string                 `protobuf:"bytes,3,opt,name=detail_file,json=detailFile,proto3" json:"detail_file,omitempty"`        // 详细格式文件名
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`                                        // 简化格式 URL
	DetailUrl     string                 `protobuf:"bytes,5,opt,name=detail_url,json=detailUrl,proto3" json:"detail_url,omitempty"`           // 详细格式 URL
	Exists        bool                   `protobuf:"varint,6,opt,name=exists,proto3" json:"exists,omitempty"`                                 // 简化格式是否存在
	DetailExists  bool                   `protobuf:"varint,7,opt,name=detail_exists,json=detailExists,proto3" json:"detail_exists,omitempty"` // 详细格式是否存在
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_ippool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{0}
}

func (x *HostInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HostInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *HostInfo) GetDetailFile() string {
	if x != nil {
		return x.DetailFile
	}
	return ""
}

func (x *HostInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HostInfo) GetDetailUrl() string {
	if x != nil {
		return x.DetailUrl
	}
	return ""
}

func (x *HostInfo) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *HostInfo) GetDetailExists() bool {
	if x != nil {
		return x.DetailExists
	}
	return false
}

// IP 地理位置信息
type IPLocationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`                         // 国家
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`                           // 地区
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`                               // 城市
	Isp           string                 `protobuf:"bytes,4,opt,name=isp,proto3" json:"isp,omitempty"`                                 // ISP
	Org           string                 `protobuf:"bytes,5,opt,name=org,proto3" json:"org,omitempty"`                                 // 组织
	DataCenter    string                 `protobuf:"bytes,6,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"` // 数据中心
	IpType        string                 `protobuf:"bytes,7,opt,name=ip_type,json=ipType,proto3" json:"ip_type,omitempty"`             // IP 类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPLocationInfo) Reset() {
	*x = IPLocationInfo{}
	mi := &file_ippool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPLocationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPLocationInfo) ProtoMessage() {}

func (x *IPLocationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPLocationInfo.ProtoReflect.Descriptor instead.
func (*IPLocationInfo) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{1}
}

func (x *IPLocationInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *IPLocationInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *IPLocationInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *IPLocationInfo) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *IPLocationInfo) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *IPLocationInfo) GetDataCenter() string {
	if x != nil {
		return x.DataCenter
	}
	return ""
}

func (x *IPLocationInfo) GetIpType() string {
	if x != nil {
		return x.IpType
	}
	return ""
}

// IP 详细信息
type IPDetailInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`             // IP 地址
	Location      *IPLocationInfo        `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"` // 地理位置信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPDetailInfo) Reset() {
	*x = IPDetailInfo{}
	mi := &file_ippool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPDetailInfo) ProtoMessage() {}

func (x *IPDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPDetailInfo.ProtoReflect.Descriptor instead.
func (*IPDetailInfo) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{2}
}

func (x *IPDetailInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPDetailInfo) GetLocation() *IPLocationInfo {
	if x != nil {
		return x.Location
	}
	return nil
}

// IP 池统计信息
type PoolStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipv4Count     int32                  `protobuf:"varint,1,opt,name=ipv4_count,json=ipv4Count,proto3" json:"ipv4_count,omitempty"`      // IPv4 数量
	Ipv6Count     int32                  `protobuf:"varint,2,opt,name=ipv6_count,json=ipv6Count,proto3" json:"ipv6_count,omitempty"`      // IPv6 数量
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"` // 最后更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolStats) Reset() {
	*x = PoolStats{}
	mi := &file_ippool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStats) ProtoMessage() {}

func (x *PoolStats) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStats.ProtoReflect.Descriptor instead.
func (*PoolStats) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{3}
}

func (x *PoolStats) GetIpv4Count() int32 {
	if x != nil {
		return x.Ipv4Count
	}
	return 0
}

func (x *PoolStats) GetIpv6Count() int32 {
	if x != nil {
		return x.Ipv6Count
	}
	return 0
}

func (x *PoolStats) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// 详细 IP 池数据
type DetailIPPoolData struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Ips           map[string]*IPDetailInfo `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // IP -> 详细信息映射
	Stats         *PoolStats               `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`                                                                       // 统计信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailIPPoolData) Reset() {
	*x = DetailIPPoolData{}
	mi := &file_ippool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailIPPoolData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailIPPoolData) ProtoMessage() {}

func (x *DetailIPPoolData) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailIPPoolData.ProtoReflect.Descriptor instead.
func (*DetailIPPoolData) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{4}
}

func (x *DetailIPPoolData) GetIps() map[string]*IPDetailInfo {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *DetailIPPoolData) GetStats() *PoolStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// 分析统计信息
type AnalyzeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalHosts    int32                  `protobuf:"varint,1,opt,name=total_hosts,json=totalHosts,proto3" json:"total_hosts,omitempty"`                                                                              // 主机总数
	TotalIpv4     int32                  `protobuf:"varint,2,opt,name=total_ipv4,json=totalIpv4,proto3" json:"total_ipv4,omitempty"`                                                                                 // IPv4 总数
	TotalIpv6     int32                  `protobuf:"varint,3,opt,name=total_ipv6,json=totalIpv6,proto3" json:"total_ipv6,omitempty"`                                                                                 // IPv6 总数
	Countries     map[string]int32       `protobuf:"bytes,4,rep,name=countries,proto3" json:"countries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`                        // 国家分布
	Cities        map[string]int32       `protobuf:"bytes,5,rep,name=cities,proto3" json:"cities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`                              // 城市分布
	Regions       map[string]int32       `protobuf:"bytes,6,rep,name=regions,proto3" json:"regions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`                            // 地区分布
	Isps          map[string]int32       `protobuf:"bytes,7,rep,name=isps,proto3" json:"isps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`                                  // ISP 分布
	Orgs          map[string]int32       `protobuf:"bytes,8,rep,name=orgs,proto3" json:"orgs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`                                  // 组织分布
	DataCenters   map[string]int32       `protobuf:"bytes,9,rep,name=data_centers,json=dataCenters,proto3" json:"data_centers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 数据中心分布
	IpTypes       map[string]int32       `protobuf:"bytes,10,rep,name=ip_types,json=ipTypes,proto3" json:"ip_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`            // IP 类型分布
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeStats) Reset() {
	*x = AnalyzeStats{}
	mi := &file_ippool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeStats) ProtoMessage() {}

func (x *AnalyzeStats) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeStats.ProtoReflect.Descriptor instead.
func (*AnalyzeStats) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzeStats) GetTotalHosts() int32 {
	if x != nil {
		return x.TotalHosts
	}
	return 0
}

func (x *AnalyzeStats) GetTotalIpv4() int32 {
	if x != nil {
		return x.TotalIpv4
	}
	return 0
}

func (x *AnalyzeStats) GetTotalIpv6() int32 {
	if x != nil {
		return x.TotalIpv6
	}
	return 0
}

func (x *AnalyzeStats) GetCountries() map[string]int32 {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *AnalyzeStats) GetCities() map[string]int32 {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *AnalyzeStats) GetRegions() map[string]int32 {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *AnalyzeStats) GetIsps() map[string]int32 {
	if x != nil {
		return x.Isps
	}
	return nil
}

func (x *AnalyzeStats) GetOrgs() map[string]int32 {
	if x != nil {
		return x.Orgs
	}
	return nil
}

func (x *AnalyzeStats) GetDataCenters() map[string]int32 {
	if x != nil {
		return x.DataCenters
	}
	return nil
}

func (x *AnalyzeStats) GetIpTypes() map[string]int32 {
	if x != nil {
		return x.IpTypes
	}
	return nil
}

// GetAllHosts
type GetAllHostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllHostsRequest) Reset() {
	*x = GetAllHostsRequest{}
	mi := &file_ippool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHostsRequest) ProtoMessage() {}

func (x *GetAllHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHostsRequest.ProtoReflect.Descriptor instead.
func (*GetAllHostsRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{6}
}

type GetAllHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*HostInfo            `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllHostsResponse) Reset() {
	*x = GetAllHostsResponse{}
	mi := &file_ippool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHostsResponse) ProtoMessage() {}

func (x *GetAllHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHostsResponse.ProtoReflect.Descriptor instead.
func (*GetAllHostsResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllHostsResponse) GetHosts() []*HostInfo {
	if x != nil {
		return x.Hosts
	}
	return nil
}

// GetHostInfo
type GetHostInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostInfoRequest) Reset() {
	*x = GetHostInfoRequest{}
	mi := &file_ippool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostInfoRequest) ProtoMessage() {}

func (x *GetHostInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostInfoRequest.ProtoReflect.Descriptor instead.
func (*GetHostInfoRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{8}
}

func (x *GetHostInfoRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type GetHostInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostInfo      *HostInfo              `protobuf:"bytes,1,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostInfoResponse) Reset() {
	*x = GetHostInfoResponse{}
	mi := &file_ippool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostInfoResponse) ProtoMessage() {}

func (x *GetHostInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostInfoResponse.ProtoReflect.Descriptor instead.
func (*GetHostInfoResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{9}
}

func (x *GetHostInfoResponse) GetHostInfo() *HostInfo {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

// GetIPPool
type GetIPPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPPoolRequest) Reset() {
	*x = GetIPPoolRequest{}
	mi := &file_ippool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPPoolRequest) ProtoMessage() {}

func (x *GetIPPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPPoolRequest.ProtoReflect.Descriptor instead.
func (*GetIPPoolRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{10}
}

func (x *GetIPPoolRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type GetIPPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipv4          []string               `protobuf:"bytes,1,rep,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          []string               `protobuf:"bytes,2,rep,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPPoolResponse) Reset() {
	*x = GetIPPoolResponse{}
	mi := &file_ippool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPPoolResponse) ProtoMessage() {}

func (x *GetIPPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPPoolResponse.ProtoReflect.Descriptor instead.
func (*GetIPPoolResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{11}
}

func (x *GetIPPoolResponse) GetIpv4() []string {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *GetIPPoolResponse) GetIpv6() []string {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

// GetDetailIPPool
type GetDetailIPPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailIPPoolRequest) Reset() {
	*x = GetDetailIPPoolRequest{}
	mi := &file_ippool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailIPPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailIPPoolRequest) ProtoMessage() {}

func (x *GetDetailIPPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailIPPoolRequest.ProtoReflect.Descriptor instead.
func (*GetDetailIPPoolRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{12}
}

func (x *GetDetailIPPoolRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type GetDetailIPPoolResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Ips           map[string]*IPDetailInfo `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // IP -> 详细信息
	Stats         *PoolStats               `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`                                                                       // 统计信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailIPPoolResponse) Reset() {
	*x = GetDetailIPPoolResponse{}
	mi := &file_ippool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailIPPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailIPPoolResponse) ProtoMessage() {}

func (x *GetDetailIPPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailIPPoolResponse.ProtoReflect.Descriptor instead.
func (*GetDetailIPPoolResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{13}
}

func (x *GetDetailIPPoolResponse) GetIps() map[string]*IPDetailInfo {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *GetDetailIPPoolResponse) GetStats() *PoolStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// GetIPDetail
type GetIPDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPDetailRequest) Reset() {
	*x = GetIPDetailRequest{}
	mi := &file_ippool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPDetailRequest) ProtoMessage() {}

func (x *GetIPDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPDetailRequest.ProtoReflect.Descriptor instead.
func (*GetIPDetailRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{14}
}

func (x *GetIPDetailRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetIPDetailRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type GetIPDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpDetail      *IPDetailInfo          `protobuf:"bytes,1,opt,name=ip_detail,json=ipDetail,proto3" json:"ip_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPDetailResponse) Reset() {
	*x = GetIPDetailResponse{}
	mi := &file_ippool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPDetailResponse) ProtoMessage() {}

func (x *GetIPDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPDetailResponse.ProtoReflect.Descriptor instead.
func (*GetIPDetailResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{15}
}

func (x *GetIPDetailResponse) GetIpDetail() *IPDetailInfo {
	if x != nil {
		return x.IpDetail
	}
	return nil
}

// SearchIPs
type SearchIPsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`                               // 主机名（可选，为空则搜索所有主机）
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`                         // 国家（可选）
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`                               // 城市（可选）
	Isp           string                 `protobuf:"bytes,4,opt,name=isp,proto3" json:"isp,omitempty"`                                 // ISP（可选）
	DataCenter    string                 `protobuf:"bytes,5,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"` // 数据中心（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchIPsRequest) Reset() {
	*x = SearchIPsRequest{}
	mi := &file_ippool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchIPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchIPsRequest) ProtoMessage() {}

func (x *SearchIPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchIPsRequest.ProtoReflect.Descriptor instead.
func (*SearchIPsRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{16}
}

func (x *SearchIPsRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SearchIPsRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *SearchIPsRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SearchIPsRequest) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *SearchIPsRequest) GetDataCenter() string {
	if x != nil {
		return x.DataCenter
	}
	return ""
}

type SearchIPsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []*IPDetailInfo        `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchIPsResponse) Reset() {
	*x = SearchIPsResponse{}
	mi := &file_ippool_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchIPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchIPsResponse) ProtoMessage() {}

func (x *SearchIPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchIPsResponse.ProtoReflect.Descriptor instead.
func (*SearchIPsResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{17}
}

func (x *SearchIPsResponse) GetIps() []*IPDetailInfo {
	if x != nil {
		return x.Ips
	}
	return nil
}

// GetRandomIP
type GetRandomIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomIPRequest) Reset() {
	*x = GetRandomIPRequest{}
	mi := &file_ippool_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomIPRequest) ProtoMessage() {}

func (x *GetRandomIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomIPRequest.ProtoReflect.Descriptor instead.
func (*GetRandomIPRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{18}
}

func (x *GetRandomIPRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type GetRandomIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomIPResponse) Reset() {
	*x = GetRandomIPResponse{}
	mi := &file_ippool_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomIPResponse) ProtoMessage() {}

func (x *GetRandomIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomIPResponse.ProtoReflect.Descriptor instead.
func (*GetRandomIPResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{19}
}

func (x *GetRandomIPResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// GetAllIPsByHost
type GetAllIPsByHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllIPsByHostRequest) Reset() {
	*x = GetAllIPsByHostRequest{}
	mi := &file_ippool_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllIPsByHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllIPsByHostRequest) ProtoMessage() {}

func (x *GetAllIPsByHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllIPsByHostRequest.ProtoReflect.Descriptor instead.
func (*GetAllIPsByHostRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{20}
}

func (x *GetAllIPsByHostRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type GetAllIPsByHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipv4          []string               `protobuf:"bytes,1,rep,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          []string               `protobuf:"bytes,2,rep,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllIPsByHostResponse) Reset() {
	*x = GetAllIPsByHostResponse{}
	mi := &file_ippool_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllIPsByHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllIPsByHostResponse) ProtoMessage() {}

func (x *GetAllIPsByHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllIPsByHostResponse.ProtoReflect.Descriptor instead.
func (*GetAllIPsByHostResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{21}
}

func (x *GetAllIPsByHostResponse) GetIpv4() []string {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *GetAllIPsByHostResponse) GetIpv6() []string {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

// AnalyzeAll
type AnalyzeAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeAllRequest) Reset() {
	*x = AnalyzeAllRequest{}
	mi := &file_ippool_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeAllRequest) ProtoMessage() {}

func (x *AnalyzeAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeAllRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeAllRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{22}
}

type AnalyzeAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *AnalyzeStats          `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeAllResponse) Reset() {
	*x = AnalyzeAllResponse{}
	mi := &file_ippool_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeAllResponse) ProtoMessage() {}

func (x *AnalyzeAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeAllResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeAllResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{23}
}

func (x *AnalyzeAllResponse) GetStats() *AnalyzeStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// AnalyzeByHost
type AnalyzeByHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeByHostRequest) Reset() {
	*x = AnalyzeByHostRequest{}
	mi := &file_ippool_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeByHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeByHostRequest) ProtoMessage() {}

func (x *AnalyzeByHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeByHostRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeByHostRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{24}
}

func (x *AnalyzeByHostRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type AnalyzeByHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *AnalyzeStats          `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeByHostResponse) Reset() {
	*x = AnalyzeByHostResponse{}
	mi := &file_ippool_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeByHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeByHostResponse) ProtoMessage() {}

func (x *AnalyzeByHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeByHostResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeByHostResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{25}
}

func (x *AnalyzeByHostResponse) GetStats() *AnalyzeStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// AnalyzeByCountry
type AnalyzeByCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeByCountryRequest) Reset() {
	*x = AnalyzeByCountryRequest{}
	mi := &file_ippool_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeByCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeByCountryRequest) ProtoMessage() {}

func (x *AnalyzeByCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeByCountryRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeByCountryRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{26}
}

func (x *AnalyzeByCountryRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type AnalyzeByCountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []*IPDetailInfo        `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeByCountryResponse) Reset() {
	*x = AnalyzeByCountryResponse{}
	mi := &file_ippool_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeByCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeByCountryResponse) ProtoMessage() {}

func (x *AnalyzeByCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeByCountryResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeByCountryResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{27}
}

func (x *AnalyzeByCountryResponse) GetIps() []*IPDetailInfo {
	if x != nil {
		return x.Ips
	}
	return nil
}

// AnalyzeByCity
type AnalyzeByCityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeByCityRequest) Reset() {
	*x = AnalyzeByCityRequest{}
	mi := &file_ippool_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeByCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeByCityRequest) ProtoMessage() {}

func (x *AnalyzeByCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeByCityRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeByCityRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{28}
}

func (x *AnalyzeByCityRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type AnalyzeByCityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []*IPDetailInfo        `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeByCityResponse) Reset() {
	*x = AnalyzeByCityResponse{}
	mi := &file_ippool_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeByCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeByCityResponse) ProtoMessage() {}

func (x *AnalyzeByCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeByCityResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeByCityResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{29}
}

func (x *AnalyzeByCityResponse) GetIps() []*IPDetailInfo {
	if x != nil {
		return x.Ips
	}
	return nil
}

// AnalyzeByISP
type AnalyzeByISPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isp           string                 `protobuf:"bytes,1,opt,name=isp,proto3" json:"isp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeByISPRequest) Reset() {
	*x = AnalyzeByISPRequest{}
	mi := &file_ippool_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeByISPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeByISPRequest) ProtoMessage() {}

func (x *AnalyzeByISPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeByISPRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeByISPRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{30}
}

func (x *AnalyzeByISPRequest) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

type AnalyzeByISPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []*IPDetailInfo        `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeByISPResponse) Reset() {
	*x = AnalyzeByISPResponse{}
	mi := &file_ippool_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeByISPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeByISPResponse) ProtoMessage() {}

func (x *AnalyzeByISPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeByISPResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeByISPResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{31}
}

func (x *AnalyzeByISPResponse) GetIps() []*IPDetailInfo {
	if x != nil {
		return x.Ips
	}
	return nil
}

// AnalyzeByDataCenter
type AnalyzeByDataCenterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataCenter    string                 `protobuf:"bytes,1,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeByDataCenterRequest) Reset() {
	*x = AnalyzeByDataCenterRequest{}
	mi := &file_ippool_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeByDataCenterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeByDataCenterRequest) ProtoMessage() {}

func (x *AnalyzeByDataCenterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeByDataCenterRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeByDataCenterRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{32}
}

func (x *AnalyzeByDataCenterRequest) GetDataCenter() string {
	if x != nil {
		return x.DataCenter
	}
	return ""
}

type AnalyzeByDataCenterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []*IPDetailInfo        `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeByDataCenterResponse) Reset() {
	*x = AnalyzeByDataCenterResponse{}
	mi := &file_ippool_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeByDataCenterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeByDataCenterResponse) ProtoMessage() {}

func (x *AnalyzeByDataCenterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeByDataCenterResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeByDataCenterResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{33}
}

func (x *AnalyzeByDataCenterResponse) GetIps() []*IPDetailInfo {
	if x != nil {
		return x.Ips
	}
	return nil
}

// SyncAll
type SyncAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"` // 是否强制同步
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAllRequest) Reset() {
	*x = SyncAllRequest{}
	mi := &file_ippool_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllRequest) ProtoMessage() {}

func (x *SyncAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllRequest.ProtoReflect.Descriptor instead.
func (*SyncAllRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{34}
}

func (x *SyncAllRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type SyncAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAllResponse) Reset() {
	*x = SyncAllResponse{}
	mi := &file_ippool_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllResponse) ProtoMessage() {}

func (x *SyncAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllResponse.ProtoReflect.Descriptor instead.
func (*SyncAllResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{35}
}

func (x *SyncAllResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncAllResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SyncHosts
type SyncHostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncHostsRequest) Reset() {
	*x = SyncHostsRequest{}
	mi := &file_ippool_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHostsRequest) ProtoMessage() {}

func (x *SyncHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHostsRequest.ProtoReflect.Descriptor instead.
func (*SyncHostsRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{36}
}

type SyncHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HostCount     int32                  `protobuf:"varint,3,opt,name=host_count,json=hostCount,proto3" json:"host_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncHostsResponse) Reset() {
	*x = SyncHostsResponse{}
	mi := &file_ippool_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHostsResponse) ProtoMessage() {}

func (x *SyncHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHostsResponse.ProtoReflect.Descriptor instead.
func (*SyncHostsResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{37}
}

func (x *SyncHostsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncHostsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncHostsResponse) GetHostCount() int32 {
	if x != nil {
		return x.HostCount
	}
	return 0
}

// SyncIPPool
type SyncIPPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncIPPoolRequest) Reset() {
	*x = SyncIPPoolRequest{}
	mi := &file_ippool_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncIPPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncIPPoolRequest) ProtoMessage() {}

func (x *SyncIPPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncIPPoolRequest.ProtoReflect.Descriptor instead.
func (*SyncIPPoolRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{38}
}

func (x *SyncIPPoolRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type SyncIPPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ipv4Count     int32                  `protobuf:"varint,3,opt,name=ipv4_count,json=ipv4Count,proto3" json:"ipv4_count,omitempty"`
	Ipv6Count     int32                  `protobuf:"varint,4,opt,name=ipv6_count,json=ipv6Count,proto3" json:"ipv6_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncIPPoolResponse) Reset() {
	*x = SyncIPPoolResponse{}
	mi := &file_ippool_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncIPPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncIPPoolResponse) ProtoMessage() {}

func (x *SyncIPPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncIPPoolResponse.ProtoReflect.Descriptor instead.
func (*SyncIPPoolResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{39}
}

func (x *SyncIPPoolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncIPPoolResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncIPPoolResponse) GetIpv4Count() int32 {
	if x != nil {
		return x.Ipv4Count
	}
	return 0
}

func (x *SyncIPPoolResponse) GetIpv6Count() int32 {
	if x != nil {
		return x.Ipv6Count
	}
	return 0
}

// SyncDetailIPPool
type SyncDetailIPPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // 是否强制更新
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDetailIPPoolRequest) Reset() {
	*x = SyncDetailIPPoolRequest{}
	mi := &file_ippool_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDetailIPPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDetailIPPoolRequest) ProtoMessage() {}

func (x *SyncDetailIPPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDetailIPPoolRequest.ProtoReflect.Descriptor instead.
func (*SyncDetailIPPoolRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{40}
}

func (x *SyncDetailIPPoolRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SyncDetailIPPoolRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type SyncDetailIPPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IpCount       int32                  `protobuf:"varint,3,opt,name=ip_count,json=ipCount,proto3" json:"ip_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDetailIPPoolResponse) Reset() {
	*x = SyncDetailIPPoolResponse{}
	mi := &file_ippool_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDetailIPPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDetailIPPoolResponse) ProtoMessage() {}

func (x *SyncDetailIPPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDetailIPPoolResponse.ProtoReflect.Descriptor instead.
func (*SyncDetailIPPoolResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{41}
}

func (x *SyncDetailIPPoolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncDetailIPPoolResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncDetailIPPoolResponse) GetIpCount() int32 {
	if x != nil {
		return x.IpCount
	}
	return 0
}

// GetServiceStatus
type GetServiceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatusRequest) Reset() {
	*x = GetServiceStatusRequest{}
	mi := &file_ippool_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatusRequest) ProtoMessage() {}

func (x *GetServiceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatusRequest.ProtoReflect.Descriptor instead.
func (*GetServiceStatusRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{42}
}

type GetServiceStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OfflineMode     bool                   `protobuf:"varint,1,opt,name=offline_mode,json=offlineMode,proto3" json:"offline_mode,omitempty"`               // 是否离线模式
	AutoSyncEnabled bool                   `protobuf:"varint,2,opt,name=auto_sync_enabled,json=autoSyncEnabled,proto3" json:"auto_sync_enabled,omitempty"` // 自动同步是否启用
	LastSyncTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`           // 最后同步时间
	TotalHosts      int32                  `protobuf:"varint,4,opt,name=total_hosts,json=totalHosts,proto3" json:"total_hosts,omitempty"`                  // 主机总数
	LoadedHosts     int32                  `protobuf:"varint,5,opt,name=loaded_hosts,json=loadedHosts,proto3" json:"loaded_hosts,omitempty"`               // 已加载主机数
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetServiceStatusResponse) Reset() {
	*x = GetServiceStatusResponse{}
	mi := &file_ippool_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatusResponse) ProtoMessage() {}

func (x *GetServiceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatusResponse.ProtoReflect.Descriptor instead.
func (*GetServiceStatusResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{43}
}

func (x *GetServiceStatusResponse) GetOfflineMode() bool {
	if x != nil {
		return x.OfflineMode
	}
	return false
}

func (x *GetServiceStatusResponse) GetAutoSyncEnabled() bool {
	if x != nil {
		return x.AutoSyncEnabled
	}
	return false
}

func (x *GetServiceStatusResponse) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

func (x *GetServiceStatusResponse) GetTotalHosts() int32 {
	if x != nil {
		return x.TotalHosts
	}
	return 0
}

func (x *GetServiceStatusResponse) GetLoadedHosts() int32 {
	if x != nil {
		return x.LoadedHosts
	}
	return 0
}

// GetCountriesList
type GetCountriesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountriesListRequest) Reset() {
	*x = GetCountriesListRequest{}
	mi := &file_ippool_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountriesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountriesListRequest) ProtoMessage() {}

func (x *GetCountriesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountriesListRequest.ProtoReflect.Descriptor instead.
func (*GetCountriesListRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{44}
}

type GetCountriesListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     map[string]int32       `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 国家名称 -> IP 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountriesListResponse) Reset() {
	*x = GetCountriesListResponse{}
	mi := &file_ippool_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountriesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountriesListResponse) ProtoMessage() {}

func (x *GetCountriesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountriesListResponse.ProtoReflect.Descriptor instead.
func (*GetCountriesListResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{45}
}

func (x *GetCountriesListResponse) GetCountries() map[string]int32 {
	if x != nil {
		return x.Countries
	}
	return nil
}

// GetCitiesByCountry
type GetCitiesByCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCitiesByCountryRequest) Reset() {
	*x = GetCitiesByCountryRequest{}
	mi := &file_ippool_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCitiesByCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesByCountryRequest) ProtoMessage() {}

func (x *GetCitiesByCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesByCountryRequest.ProtoReflect.Descriptor instead.
func (*GetCitiesByCountryRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{46}
}

func (x *GetCitiesByCountryRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GetCitiesByCountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cities        map[string]int32       `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 城市名称 -> IP 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCitiesByCountryResponse) Reset() {
	*x = GetCitiesByCountryResponse{}
	mi := &file_ippool_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCitiesByCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesByCountryResponse) ProtoMessage() {}

func (x *GetCitiesByCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesByCountryResponse.ProtoReflect.Descriptor instead.
func (*GetCitiesByCountryResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{47}
}

func (x *GetCitiesByCountryResponse) GetCities() map[string]int32 {
	if x != nil {
		return x.Cities
	}
	return nil
}

// GetIPsByCountryAndCity
type GetIPsByCountryAndCityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"` // 国家（可选，为空则返回所有国家）
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`       // 城市（可选，为空则返回该国家的所有城市）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPsByCountryAndCityRequest) Reset() {
	*x = GetIPsByCountryAndCityRequest{}
	mi := &file_ippool_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPsByCountryAndCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPsByCountryAndCityRequest) ProtoMessage() {}

func (x *GetIPsByCountryAndCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPsByCountryAndCityRequest.ProtoReflect.Descriptor instead.
func (*GetIPsByCountryAndCityRequest) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{48}
}

func (x *GetIPsByCountryAndCityRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetIPsByCountryAndCityRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetIPsByCountryAndCityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []*IPDetailInfo        `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"` // IP 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPsByCountryAndCityResponse) Reset() {
	*x = GetIPsByCountryAndCityResponse{}
	mi := &file_ippool_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPsByCountryAndCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPsByCountryAndCityResponse) ProtoMessage() {}

func (x *GetIPsByCountryAndCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPsByCountryAndCityResponse.ProtoReflect.Descriptor instead.
func (*GetIPsByCountryAndCityResponse) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{49}
}

func (x *GetIPsByCountryAndCityResponse) GetIps() []*IPDetailInfo {
	if x != nil {
		return x.Ips
	}
	return nil
}

var File_ippool_proto protoreflect.FileDescriptor

const file_ippool_proto_rawDesc = "" +
	"\n" +
	"\fippool.proto\x12\x06ippool\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n" +
	"\bHostInfo\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1f\n" +
	"\vdetail_file\x18\x03 \x01(\tR\n" +
	"detailFile\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"detail_url\x18\x05 \x01(\tR\tdetailUrl\x12\x16\n" +
	"\x06exists\x18\x06 \x01(\bR\x06exists\x12#\n" +
	"\rdetail_exists\x18\a \x01(\bR\fdetailExists\"\xb4\x01\n" +
	"\x0eIPLocationInfo\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x10\n" +
	"\x03isp\x18\x04 \x01(\tR\x03isp\x12\x10\n" +
	"\x03org\x18\x05 \x01(\tR\x03org\x12\x1f\n" +
	"\vdata_center\x18\x06 \x01(\tR\n" +
	"dataCenter\x12\x17\n" +
	"\aip_type\x18\a \x01(\tR\x06ipType\"R\n" +
	"\fIPDetailInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x122\n" +
	"\blocation\x18\x02 \x01(\v2\x16.ippool.IPLocationInfoR\blocation\"\x88\x01\n" +
	"\tPoolStats\x12\x1d\n" +
	"\n" +
	"ipv4_count\x18\x01 \x01(\x05R\tipv4Count\x12\x1d\n" +
	"\n" +
	"ipv6_count\x18\x02 \x01(\x05R\tipv6Count\x12=\n" +
	"\flast_updated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\xbe\x01\n" +
	"\x10DetailIPPoolData\x123\n" +
	"\x03ips\x18\x01 \x03(\v2!.ippool.DetailIPPoolData.IpsEntryR\x03ips\x12'\n" +
	"\x05stats\x18\x02 \x01(\v2\x11.ippool.PoolStatsR\x05stats\x1aL\n" +
	"\bIpsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.ippool.IPDetailInfoR\x05value:\x028\x01\"\xba\a\n" +
	"\fAnalyzeStats\x12\x1f\n" +
	"\vtotal_hosts\x18\x01 \x01(\x05R\n" +
	"totalHosts\x12\x1d\n" +
	"\n" +
	"total_ipv4\x18\x02 \x01(\x05R\ttotalIpv4\x12\x1d\n" +
	"\n" +
	"total_ipv6\x18\x03 \x01(\x05R\ttotalIpv6\x12A\n" +
	"\tcountries\x18\x04 \x03(\v2#.ippool.AnalyzeStats.CountriesEntryR\tcountries\x128\n" +
	"\x06cities\x18\x05 \x03(\v2 .ippool.AnalyzeStats.CitiesEntryR\x06cities\x12;\n" +
	"\aregions\x18\x06 \x03(\v2!.ippool.AnalyzeStats.RegionsEntryR\aregions\x122\n" +
	"\x04isps\x18\a \x03(\v2\x1e.ippool.AnalyzeStats.IspsEntryR\x04isps\x122\n" +
	"\x04orgs\x18\b \x03(\v2\x1e.ippool.AnalyzeStats.OrgsEntryR\x04orgs\x12H\n" +
	"\fdata_centers\x18\t \x03(\v2%.ippool.AnalyzeStats.DataCentersEntryR\vdataCenters\x12<\n" +
	"\bip_types\x18\n" +
	" \x03(\v2!.ippool.AnalyzeStats.IpTypesEntryR\aipTypes\x1a<\n" +
	"\x0eCountriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a9\n" +
	"\vCitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a:\n" +
	"\fRegionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a7\n" +
	"\tIspsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a7\n" +
	"\tOrgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a>\n" +
	"\x10DataCentersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a:\n" +
	"\fIpTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x14\n" +
	"\x12GetAllHostsRequest\"=\n" +
	"\x13GetAllHostsResponse\x12&\n" +
	"\x05hosts\x18\x01 \x03(\v2\x10.ippool.HostInfoR\x05hosts\"(\n" +
	"\x12GetHostInfoRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"D\n" +
	"\x13GetHostInfoResponse\x12-\n" +
	"\thost_info\x18\x01 \x01(\v2\x10.ippool.HostInfoR\bhostInfo\"&\n" +
	"\x10GetIPPoolRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\";\n" +
	"\x11GetIPPoolResponse\x12\x12\n" +
	"\x04ipv4\x18\x01 \x03(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x02 \x03(\tR\x04ipv6\",\n" +
	"\x16GetDetailIPPoolRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"\xcc\x01\n" +
	"\x17GetDetailIPPoolResponse\x12:\n" +
	"\x03ips\x18\x01 \x03(\v2(.ippool.GetDetailIPPoolResponse.IpsEntryR\x03ips\x12'\n" +
	"\x05stats\x18\x02 \x01(\v2\x11.ippool.PoolStatsR\x05stats\x1aL\n" +
	"\bIpsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.ippool.IPDetailInfoR\x05value:\x028\x01\"8\n" +
	"\x12GetIPDetailRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"H\n" +
	"\x13GetIPDetailResponse\x121\n" +
	"\tip_detail\x18\x01 \x01(\v2\x14.ippool.IPDetailInfoR\bipDetail\"\x87\x01\n" +
	"\x10SearchIPsRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x10\n" +
	"\x03isp\x18\x04 \x01(\tR\x03isp\x12\x1f\n" +
	"\vdata_center\x18\x05 \x01(\tR\n" +
	"dataCenter\";\n" +
	"\x11SearchIPsResponse\x12&\n" +
	"\x03ips\x18\x01 \x03(\v2\x14.ippool.IPDetailInfoR\x03ips\"(\n" +
	"\x12GetRandomIPRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"%\n" +
	"\x13GetRandomIPResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\",\n" +
	"\x16GetAllIPsByHostRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"A\n" +
	"\x17GetAllIPsByHostResponse\x12\x12\n" +
	"\x04ipv4\x18\x01 \x03(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x02 \x03(\tR\x04ipv6\"\x13\n" +
	"\x11AnalyzeAllRequest\"@\n" +
	"\x12AnalyzeAllResponse\x12*\n" +
	"\x05stats\x18\x01 \x01(\v2\x14.ippool.AnalyzeStatsR\x05stats\"*\n" +
	"\x14AnalyzeByHostRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"C\n" +
	"\x15AnalyzeByHostResponse\x12*\n" +
	"\x05stats\x18\x01 \x01(\v2\x14.ippool.AnalyzeStatsR\x05stats\"3\n" +
	"\x17AnalyzeByCountryRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\"B\n" +
	"\x18AnalyzeByCountryResponse\x12&\n" +
	"\x03ips\x18\x01 \x03(\v2\x14.ippool.IPDetailInfoR\x03ips\"*\n" +
	"\x14AnalyzeByCityRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\"?\n" +
	"\x15AnalyzeByCityResponse\x12&\n" +
	"\x03ips\x18\x01 \x03(\v2\x14.ippool.IPDetailInfoR\x03ips\"'\n" +
	"\x13AnalyzeByISPRequest\x12\x10\n" +
	"\x03isp\x18\x01 \x01(\tR\x03isp\">\n" +
	"\x14AnalyzeByISPResponse\x12&\n" +
	"\x03ips\x18\x01 \x03(\v2\x14.ippool.IPDetailInfoR\x03ips\"=\n" +
	"\x1aAnalyzeByDataCenterRequest\x12\x1f\n" +
	"\vdata_center\x18\x01 \x01(\tR\n" +
	"dataCenter\"E\n" +
	"\x1bAnalyzeByDataCenterResponse\x12&\n" +
	"\x03ips\x18\x01 \x03(\v2\x14.ippool.IPDetailInfoR\x03ips\"&\n" +
	"\x0eSyncAllRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"E\n" +
	"\x0fSyncAllResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10SyncHostsRequest\"f\n" +
	"\x11SyncHostsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"host_count\x18\x03 \x01(\x05R\thostCount\"'\n" +
	"\x11SyncIPPoolRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"\x86\x01\n" +
	"\x12SyncIPPoolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"ipv4_count\x18\x03 \x01(\x05R\tipv4Count\x12\x1d\n" +
	"\n" +
	"ipv6_count\x18\x04 \x01(\x05R\tipv6Count\"C\n" +
	"\x17SyncDetailIPPoolRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"i\n" +
	"\x18SyncDetailIPPoolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bip_count\x18\x03 \x01(\x05R\aipCount\"\x19\n" +
	"\x17GetServiceStatusRequest\"\xef\x01\n" +
	"\x18GetServiceStatusResponse\x12!\n" +
	"\foffline_mode\x18\x01 \x01(\bR\vofflineMode\x12*\n" +
	"\x11auto_sync_enabled\x18\x02 \x01(\bR\x0fautoSyncEnabled\x12@\n" +
	"\x0elast_sync_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\x12\x1f\n" +
	"\vtotal_hosts\x18\x04 \x01(\x05R\n" +
	"totalHosts\x12!\n" +
	"\floaded_hosts\x18\x05 \x01(\x05R\vloadedHosts\"\x19\n" +
	"\x17GetCountriesListRequest\"\xa7\x01\n" +
	"\x18GetCountriesListResponse\x12M\n" +
	"\tcountries\x18\x01 \x03(\v2/.ippool.GetCountriesListResponse.CountriesEntryR\tcountries\x1a<\n" +
	"\x0eCountriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"5\n" +
	"\x19GetCitiesByCountryRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\"\x9f\x01\n" +
	"\x1aGetCitiesByCountryResponse\x12F\n" +
	"\x06cities\x18\x01 \x03(\v2..ippool.GetCitiesByCountryResponse.CitiesEntryR\x06cities\x1a9\n" +
	"\vCitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"M\n" +
	"\x1dGetIPsByCountryAndCityRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\"H\n" +
	"\x1eGetIPsByCountryAndCityResponse\x12&\n" +
	"\x03ips\x18\x01 \x03(\v2\x14.ippool.IPDetailInfoR\x03ips2\xcc\r\n" +
	"\rIPPoolService\x12F\n" +
	"\vGetAllHosts\x12\x1a.ippool.GetAllHostsRequest\x1a\x1b.ippool.GetAllHostsResponse\x12F\n" +
	"\vGetHostInfo\x12\x1a.ippool.GetHostInfoRequest\x1a\x1b.ippool.GetHostInfoResponse\x12@\n" +
	"\tGetIPPool\x12\x18.ippool.GetIPPoolRequest\x1a\x19.ippool.GetIPPoolResponse\x12R\n" +
	"\x0fGetDetailIPPool\x12\x1e.ippool.GetDetailIPPoolRequest\x1a\x1f.ippool.GetDetailIPPoolResponse\x12F\n" +
	"\vGetIPDetail\x12\x1a.ippool.GetIPDetailRequest\x1a\x1b.ippool.GetIPDetailResponse\x12@\n" +
	"\tSearchIPs\x12\x18.ippool.SearchIPsRequest\x1a\x19.ippool.SearchIPsResponse\x12F\n" +
	"\vGetRandomIP\x12\x1a.ippool.GetRandomIPRequest\x1a\x1b.ippool.GetRandomIPResponse\x12R\n" +
	"\x0fGetAllIPsByHost\x12\x1e.ippool.GetAllIPsByHostRequest\x1a\x1f.ippool.GetAllIPsByHostResponse\x12C\n" +
	"\n" +
	"AnalyzeAll\x12\x19.ippool.AnalyzeAllRequest\x1a\x1a.ippool.AnalyzeAllResponse\x12L\n" +
	"\rAnalyzeByHost\x12\x1c.ippool.AnalyzeByHostRequest\x1a\x1d.ippool.AnalyzeByHostResponse\x12U\n" +
	"\x10AnalyzeByCountry\x12\x1f.ippool.AnalyzeByCountryRequest\x1a .ippool.AnalyzeByCountryResponse\x12L\n" +
	"\rAnalyzeByCity\x12\x1c.ippool.AnalyzeByCityRequest\x1a\x1d.ippool.AnalyzeByCityResponse\x12I\n" +
	"\fAnalyzeByISP\x12\x1b.ippool.AnalyzeByISPRequest\x1a\x1c.ippool.AnalyzeByISPResponse\x12^\n" +
	"\x13AnalyzeByDataCenter\x12\".ippool.AnalyzeByDataCenterRequest\x1a#.ippool.AnalyzeByDataCenterResponse\x12U\n" +
	"\x10GetCountriesList\x12\x1f.ippool.GetCountriesListRequest\x1a .ippool.GetCountriesListResponse\x12[\n" +
	"\x12GetCitiesByCountry\x12!.ippool.GetCitiesByCountryRequest\x1a\".ippool.GetCitiesByCountryResponse\x12g\n" +
	"\x16GetIPsByCountryAndCity\x12%.ippool.GetIPsByCountryAndCityRequest\x1a&.ippool.GetIPsByCountryAndCityResponse\x12:\n" +
	"\aSyncAll\x12\x16.ippool.SyncAllRequest\x1a\x17.ippool.SyncAllResponse\x12@\n" +
	"\tSyncHosts\x12\x18.ippool.SyncHostsRequest\x1a\x19.ippool.SyncHostsResponse\x12C\n" +
	"\n" +
	"SyncIPPool\x12\x19.ippool.SyncIPPoolRequest\x1a\x1a.ippool.SyncIPPoolResponse\x12U\n" +
	"\x10SyncDetailIPPool\x12\x1f.ippool.SyncDetailIPPoolRequest\x1a .ippool.SyncDetailIPPoolResponse\x12U\n" +
	"\x10GetServiceStatus\x12\x1f.ippool.GetServiceStatusRequest\x1a .ippool.GetServiceStatusResponseB\x1aZ\x18utls_client/proto/ippoolb\x06proto3"

var (
	file_ippool_proto_rawDescOnce sync.Once
	file_ippool_proto_rawDescData []byte
)

func file_ippool_proto_rawDescGZIP() []byte {
	file_ippool_proto_rawDescOnce.Do(func() {
		file_ippool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ippool_proto_rawDesc), len(file_ippool_proto_rawDesc)))
	})
	return file_ippool_proto_rawDescData
}

var file_ippool_proto_msgTypes = make([]protoimpl.MessageInfo, 61)
var file_ippool_proto_goTypes = []any{
	(*HostInfo)(nil),                       // 0: ippool.HostInfo
	(*IPLocationInfo)(nil),                 // 1: ippool.IPLocationInfo
	(*IPDetailInfo)(nil),                   // 2: ippool.IPDetailInfo
	(*PoolStats)(nil),                      // 3: ippool.PoolStats
	(*DetailIPPoolData)(nil),               // 4: ippool.DetailIPPoolData
	(*AnalyzeStats)(nil),                   // 5: ippool.AnalyzeStats
	(*GetAllHostsRequest)(nil),             // 6: ippool.GetAllHostsRequest
	(*GetAllHostsResponse)(nil),            // 7: ippool.GetAllHostsResponse
	(*GetHostInfoRequest)(nil),             // 8: ippool.GetHostInfoRequest
	(*GetHostInfoResponse)(nil),            // 9: ippool.GetHostInfoResponse
	(*GetIPPoolRequest)(nil),               // 10: ippool.GetIPPoolRequest
	(*GetIPPoolResponse)(nil),              // 11: ippool.GetIPPoolResponse
	(*GetDetailIPPoolRequest)(nil),         // 12: ippool.GetDetailIPPoolRequest
	(*GetDetailIPPoolResponse)(nil),        // 13: ippool.GetDetailIPPoolResponse
	(*GetIPDetailRequest)(nil),             // 14: ippool.GetIPDetailRequest
	(*GetIPDetailResponse)(nil),            // 15: ippool.GetIPDetailResponse
	(*SearchIPsRequest)(nil),               // 16: ippool.SearchIPsRequest
	(*SearchIPsResponse)(nil),              // 17: ippool.SearchIPsResponse
	(*GetRandomIPRequest)(nil),             // 18: ippool.GetRandomIPRequest
	(*GetRandomIPResponse)(nil),            // 19: ippool.GetRandomIPResponse
	(*GetAllIPsByHostRequest)(nil),         // 20: ippool.GetAllIPsByHostRequest
	(*GetAllIPsByHostResponse)(nil),        // 21: ippool.GetAllIPsByHostResponse
	(*AnalyzeAllRequest)(nil),              // 22: ippool.AnalyzeAllRequest
	(*AnalyzeAllResponse)(nil),             // 23: ippool.AnalyzeAllResponse
	(*AnalyzeByHostRequest)(nil),           // 24: ippool.AnalyzeByHostRequest
	(*AnalyzeByHostResponse)(nil),          // 25: ippool.AnalyzeByHostResponse
	(*AnalyzeByCountryRequest)(nil),        // 26: ippool.AnalyzeByCountryRequest
	(*AnalyzeByCountryResponse)(nil),       // 27: ippool.AnalyzeByCountryResponse
	(*AnalyzeByCityRequest)(nil),           // 28: ippool.AnalyzeByCityRequest
	(*AnalyzeByCityResponse)(nil),          // 29: ippool.AnalyzeByCityResponse
	(*AnalyzeByISPRequest)(nil),            // 30: ippool.AnalyzeByISPRequest
	(*AnalyzeByISPResponse)(nil),           // 31: ippool.AnalyzeByISPResponse
	(*AnalyzeByDataCenterRequest)(nil),     // 32: ippool.AnalyzeByDataCenterRequest
	(*AnalyzeByDataCenterResponse)(nil),    // 33: ippool.AnalyzeByDataCenterResponse
	(*SyncAllRequest)(nil),                 // 34: ippool.SyncAllRequest
	(*SyncAllResponse)(nil),                // 35: ippool.SyncAllResponse
	(*SyncHostsRequest)(nil),               // 36: ippool.SyncHostsRequest
	(*SyncHostsResponse)(nil),              // 37: ippool.SyncHostsResponse
	(*SyncIPPoolRequest)(nil),              // 38: ippool.SyncIPPoolRequest
	(*SyncIPPoolResponse)(nil),             // 39: ippool.SyncIPPoolResponse
	(*SyncDetailIPPoolRequest)(nil),        // 40: ippool.SyncDetailIPPoolRequest
	(*SyncDetailIPPoolResponse)(nil),       // 41: ippool.SyncDetailIPPoolResponse
	(*GetServiceStatusRequest)(nil),        // 42: ippool.GetServiceStatusRequest
	(*GetServiceStatusResponse)(nil),       // 43: ippool.GetServiceStatusResponse
	(*GetCountriesListRequest)(nil),        // 44: ippool.GetCountriesListRequest
	(*GetCountriesListResponse)(nil),       // 45: ippool.GetCountriesListResponse
	(*GetCitiesByCountryRequest)(nil),      // 46: ippool.GetCitiesByCountryRequest
	(*GetCitiesByCountryResponse)(nil),     // 47: ippool.GetCitiesByCountryResponse
	(*GetIPsByCountryAndCityRequest)(nil),  // 48: ippool.GetIPsByCountryAndCityRequest
	(*GetIPsByCountryAndCityResponse)(nil), // 49: ippool.GetIPsByCountryAndCityResponse
	nil,                                    // 50: ippool.DetailIPPoolData.IpsEntry
	nil,                                    // 51: ippool.AnalyzeStats.CountriesEntry
	nil,                                    // 52: ippool.AnalyzeStats.CitiesEntry
	nil,                                    // 53: ippool.AnalyzeStats.RegionsEntry
	nil,                                    // 54: ippool.AnalyzeStats.IspsEntry
	nil,                                    // 55: ippool.AnalyzeStats.OrgsEntry
	nil,                                    // 56: ippool.AnalyzeStats.DataCentersEntry
	nil,                                    // 57: ippool.AnalyzeStats.IpTypesEntry
	nil,                                    // 58: ippool.GetDetailIPPoolResponse.IpsEntry
	nil,                                    // 59: ippool.GetCountriesListResponse.CountriesEntry
	nil,                                    // 60: ippool.GetCitiesByCountryResponse.CitiesEntry
	(*timestamppb.Timestamp)(nil),          // 61: google.protobuf.Timestamp
}
var file_ippool_proto_depIdxs = []int32{
	1,  // 0: ippool.IPDetailInfo.location:type_name -> ippool.IPLocationInfo
	61, // 1: ippool.PoolStats.last_updated:type_name -> google.protobuf.Timestamp
	50, // 2: ippool.DetailIPPoolData.ips:type_name -> ippool.DetailIPPoolData.IpsEntry
	3,  // 3: ippool.DetailIPPoolData.stats:type_name -> ippool.PoolStats
	51, // 4: ippool.AnalyzeStats.countries:type_name -> ippool.AnalyzeStats.CountriesEntry
	52, // 5: ippool.AnalyzeStats.cities:type_name -> ippool.AnalyzeStats.CitiesEntry
	53, // 6: ippool.AnalyzeStats.regions:type_name -> ippool.AnalyzeStats.RegionsEntry
	54, // 7: ippool.AnalyzeStats.isps:type_name -> ippool.AnalyzeStats.IspsEntry
	55, // 8: ippool.AnalyzeStats.orgs:type_name -> ippool.AnalyzeStats.OrgsEntry
	56, // 9: ippool.AnalyzeStats.data_centers:type_name -> ippool.AnalyzeStats.DataCentersEntry
	57, // 10: ippool.AnalyzeStats.ip_types:type_name -> ippool.AnalyzeStats.IpTypesEntry
	0,  // 11: ippool.GetAllHostsResponse.hosts:type_name -> ippool.HostInfo
	0,  // 12: ippool.GetHostInfoResponse.host_info:type_name -> ippool.HostInfo
	58, // 13: ippool.GetDetailIPPoolResponse.ips:type_name -> ippool.GetDetailIPPoolResponse.IpsEntry
	3,  // 14: ippool.GetDetailIPPoolResponse.stats:type_name -> ippool.PoolStats
	2,  // 15: ippool.GetIPDetailResponse.ip_detail:type_name -> ippool.IPDetailInfo
	2,  // 16: ippool.SearchIPsResponse.ips:type_name -> ippool.IPDetailInfo
	5,  // 17: ippool.AnalyzeAllResponse.stats:type_name -> ippool.AnalyzeStats
	5,  // 18: ippool.AnalyzeByHostResponse.stats:type_name -> ippool.AnalyzeStats
	2,  // 19: ippool.AnalyzeByCountryResponse.ips:type_name -> ippool.IPDetailInfo
	2,  // 20: ippool.AnalyzeByCityResponse.ips:type_name -> ippool.IPDetailInfo
	2,  // 21: ippool.AnalyzeByISPResponse.ips:type_name -> ippool.IPDetailInfo
	2,  // 22: ippool.AnalyzeByDataCenterResponse.ips:type_name -> ippool.IPDetailInfo
	61, // 23: ippool.GetServiceStatusResponse.last_sync_time:type_name -> google.protobuf.Timestamp
	59, // 24: ippool.GetCountriesListResponse.countries:type_name -> ippool.GetCountriesListResponse.CountriesEntry
	60, // 25: ippool.GetCitiesByCountryResponse.cities:type_name -> ippool.GetCitiesByCountryResponse.CitiesEntry
	2,  // 26: ippool.GetIPsByCountryAndCityResponse.ips:type_name -> ippool.IPDetailInfo
	2,  // 27: ippool.DetailIPPoolData.IpsEntry.value:type_name -> ippool.IPDetailInfo
	2,  // 28: ippool.GetDetailIPPoolResponse.IpsEntry.value:type_name -> ippool.IPDetailInfo
	6,  // 29: ippool.IPPoolService.GetAllHosts:input_type -> ippool.GetAllHostsRequest
	8,  // 30: ippool.IPPoolService.GetHostInfo:input_type -> ippool.GetHostInfoRequest
	10, // 31: ippool.IPPoolService.GetIPPool:input_type -> ippool.GetIPPoolRequest
	12, // 32: ippool.IPPoolService.GetDetailIPPool:input_type -> ippool.GetDetailIPPoolRequest
	14, // 33: ippool.IPPoolService.GetIPDetail:input_type -> ippool.GetIPDetailRequest
	16, // 34: ippool.IPPoolService.SearchIPs:input_type -> ippool.SearchIPsRequest
	18, // 35: ippool.IPPoolService.GetRandomIP:input_type -> ippool.GetRandomIPRequest
	20, // 36: ippool.IPPoolService.GetAllIPsByHost:input_type -> ippool.GetAllIPsByHostRequest
	22, // 37: ippool.IPPoolService.AnalyzeAll:input_type -> ippool.AnalyzeAllRequest
	24, // 38: ippool.IPPoolService.AnalyzeByHost:input_type -> ippool.AnalyzeByHostRequest
	26, // 39: ippool.IPPoolService.AnalyzeByCountry:input_type -> ippool.AnalyzeByCountryRequest
	28, // 40: ippool.IPPoolService.AnalyzeByCity:input_type -> ippool.AnalyzeByCityRequest
	30, // 41: ippool.IPPoolService.AnalyzeByISP:input_type -> ippool.AnalyzeByISPRequest
	32, // 42: ippool.IPPoolService.AnalyzeByDataCenter:input_type -> ippool.AnalyzeByDataCenterRequest
	44, // 43: ippool.IPPoolService.GetCountriesList:input_type -> ippool.GetCountriesListRequest
	46, // 44: ippool.IPPoolService.GetCitiesByCountry:input_type -> ippool.GetCitiesByCountryRequest
	48, // 45: ippool.IPPoolService.GetIPsByCountryAndCity:input_type -> ippool.GetIPsByCountryAndCityRequest
	34, // 46: ippool.IPPoolService.SyncAll:input_type -> ippool.SyncAllRequest
	36, // 47: ippool.IPPoolService.SyncHosts:input_type -> ippool.SyncHostsRequest
	38, // 48: ippool.IPPoolService.SyncIPPool:input_type -> ippool.SyncIPPoolRequest
	40, // 49: ippool.IPPoolService.SyncDetailIPPool:input_type -> ippool.SyncDetailIPPoolRequest
	42, // 50: ippool.IPPoolService.GetServiceStatus:input_type -> ippool.GetServiceStatusRequest
	7,  // 51: ippool.IPPoolService.GetAllHosts:output_type -> ippool.GetAllHostsResponse
	9,  // 52: ippool.IPPoolService.GetHostInfo:output_type -> ippool.GetHostInfoResponse
	11, // 53: ippool.IPPoolService.GetIPPool:output_type -> ippool.GetIPPoolResponse
	13, // 54: ippool.IPPoolService.GetDetailIPPool:output_type -> ippool.GetDetailIPPoolResponse
	15, // 55: ippool.IPPoolService.GetIPDetail:output_type -> ippool.GetIPDetailResponse
	17, // 56: ippool.IPPoolService.SearchIPs:output_type -> ippool.SearchIPsResponse
	19, // 57: ippool.IPPoolService.GetRandomIP:output_type -> ippool.GetRandomIPResponse
	21, // 58: ippool.IPPoolService.GetAllIPsByHost:output_type -> ippool.GetAllIPsByHostResponse
	23, // 59: ippool.IPPoolService.AnalyzeAll:output_type -> ippool.AnalyzeAllResponse
	25, // 60: ippool.IPPoolService.AnalyzeByHost:output_type -> ippool.AnalyzeByHostResponse
	27, // 61: ippool.IPPoolService.AnalyzeByCountry:output_type -> ippool.AnalyzeByCountryResponse
	29, // 62: ippool.IPPoolService.AnalyzeByCity:output_type -> ippool.AnalyzeByCityResponse
	31, // 63: ippool.IPPoolService.AnalyzeByISP:output_type -> ippool.AnalyzeByISPResponse
	33, // 64: ippool.IPPoolService.AnalyzeByDataCenter:output_type -> ippool.AnalyzeByDataCenterResponse
	45, // 65: ippool.IPPoolService.GetCountriesList:output_type -> ippool.GetCountriesListResponse
	47, // 66: ippool.IPPoolService.GetCitiesByCountry:output_type -> ippool.GetCitiesByCountryResponse
	49, // 67: ippool.IPPoolService.GetIPsByCountryAndCity:output_type -> ippool.GetIPsByCountryAndCityResponse
	35, // 68: ippool.IPPoolService.SyncAll:output_type -> ippool.SyncAllResponse
	37, // 69: ippool.IPPoolService.SyncHosts:output_type -> ippool.SyncHostsResponse
	39, // 70: ippool.IPPoolService.SyncIPPool:output_type -> ippool.SyncIPPoolResponse
	41, // 71: ippool.IPPoolService.SyncDetailIPPool:output_type -> ippool.SyncDetailIPPoolResponse
	43, // 72: ippool.IPPoolService.GetServiceStatus:output_type -> ippool.GetServiceStatusResponse
	51, // [51:73] is the sub-list for method output_type
	29, // [29:51] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_ippool_proto_init() }
func file_ippool_proto_init() {
	if File_ippool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ippool_proto_rawDesc), len(file_ippool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   61,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ippool_proto_goTypes,
		DependencyIndexes: file_ippool_proto_depIdxs,
		MessageInfos:      file_ippool_proto_msgTypes,
	}.Build()
	File_ippool_proto = out.File
	file_ippool_proto_goTypes = nil
	file_ippool_proto_depIdxs = nil
}
