// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: httpforward.proto

package httpforward

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HTTPForwardService_Handshake_FullMethodName      = "/httpforward.HTTPForwardService/Handshake"
	HTTPForwardService_ForwardRequest_FullMethodName = "/httpforward.HTTPForwardService/ForwardRequest"
)

// HTTPForwardServiceClient is the client API for HTTPForwardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HTTP 转发服务
type HTTPForwardServiceClient interface {
	// 客户端握手（首次连接，获取编码）
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// 转发 HTTP 请求（使用 uTLS 客户端）
	ForwardRequest(ctx context.Context, in *ForwardRequestRequest, opts ...grpc.CallOption) (*ForwardRequestResponse, error)
}

type hTTPForwardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHTTPForwardServiceClient(cc grpc.ClientConnInterface) HTTPForwardServiceClient {
	return &hTTPForwardServiceClient{cc}
}

func (c *hTTPForwardServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, HTTPForwardService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPForwardServiceClient) ForwardRequest(ctx context.Context, in *ForwardRequestRequest, opts ...grpc.CallOption) (*ForwardRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardRequestResponse)
	err := c.cc.Invoke(ctx, HTTPForwardService_ForwardRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HTTPForwardServiceServer is the server API for HTTPForwardService service.
// All implementations must embed UnimplementedHTTPForwardServiceServer
// for forward compatibility.
//
// HTTP 转发服务
type HTTPForwardServiceServer interface {
	// 客户端握手（首次连接，获取编码）
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// 转发 HTTP 请求（使用 uTLS 客户端）
	ForwardRequest(context.Context, *ForwardRequestRequest) (*ForwardRequestResponse, error)
	mustEmbedUnimplementedHTTPForwardServiceServer()
}

// UnimplementedHTTPForwardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHTTPForwardServiceServer struct{}

func (UnimplementedHTTPForwardServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedHTTPForwardServiceServer) ForwardRequest(context.Context, *ForwardRequestRequest) (*ForwardRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardRequest not implemented")
}
func (UnimplementedHTTPForwardServiceServer) mustEmbedUnimplementedHTTPForwardServiceServer() {}
func (UnimplementedHTTPForwardServiceServer) testEmbeddedByValue()                            {}

// UnsafeHTTPForwardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HTTPForwardServiceServer will
// result in compilation errors.
type UnsafeHTTPForwardServiceServer interface {
	mustEmbedUnimplementedHTTPForwardServiceServer()
}

func RegisterHTTPForwardServiceServer(s grpc.ServiceRegistrar, srv HTTPForwardServiceServer) {
	// If the following call pancis, it indicates UnimplementedHTTPForwardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HTTPForwardService_ServiceDesc, srv)
}

func _HTTPForwardService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPForwardServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPForwardService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPForwardServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPForwardService_ForwardRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPForwardServiceServer).ForwardRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPForwardService_ForwardRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPForwardServiceServer).ForwardRequest(ctx, req.(*ForwardRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HTTPForwardService_ServiceDesc is the grpc.ServiceDesc for HTTPForwardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HTTPForwardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "httpforward.HTTPForwardService",
	HandlerType: (*HTTPForwardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _HTTPForwardService_Handshake_Handler,
		},
		{
			MethodName: "ForwardRequest",
			Handler:    _HTTPForwardService_ForwardRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "httpforward.proto",
}
