// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: httpforward.proto

package httpforward

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 握手请求（首次连接）
type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIp      string                 `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"` // 客户端 IP 地址（仅首次需要）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_httpforward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_httpforward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_httpforward_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

// 握手响应（分配编码）
type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCode    int32                  `protobuf:"varint,1,opt,name=client_code,json=clientCode,proto3" json:"client_code,omitempty"` // 分配的客户端编码（1,2,3,4...）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_httpforward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_httpforward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_httpforward_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetClientCode() int32 {
	if x != nil {
		return x.ClientCode
	}
	return 0
}

// 转发请求
type ForwardRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ClientId:
	//
	//	*ForwardRequestRequest_ClientIp
	//	*ForwardRequestRequest_ClientCode
	ClientId isForwardRequestRequest_ClientId `protobuf_oneof:"client_id"`
	// Types that are valid to be assigned to Hostname:
	//
	//	*ForwardRequestRequest_HostnameRaw
	//	*ForwardRequestRequest_HostnameCode
	Hostname      isForwardRequestRequest_Hostname `protobuf_oneof:"hostname"`
	Path          string                           `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"` // 请求路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequestRequest) Reset() {
	*x = ForwardRequestRequest{}
	mi := &file_httpforward_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequestRequest) ProtoMessage() {}

func (x *ForwardRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_httpforward_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequestRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequestRequest) Descriptor() ([]byte, []int) {
	return file_httpforward_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardRequestRequest) GetClientId() isForwardRequestRequest_ClientId {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *ForwardRequestRequest) GetClientIp() string {
	if x != nil {
		if x, ok := x.ClientId.(*ForwardRequestRequest_ClientIp); ok {
			return x.ClientIp
		}
	}
	return ""
}

func (x *ForwardRequestRequest) GetClientCode() int32 {
	if x != nil {
		if x, ok := x.ClientId.(*ForwardRequestRequest_ClientCode); ok {
			return x.ClientCode
		}
	}
	return 0
}

func (x *ForwardRequestRequest) GetHostname() isForwardRequestRequest_Hostname {
	if x != nil {
		return x.Hostname
	}
	return nil
}

func (x *ForwardRequestRequest) GetHostnameRaw() string {
	if x != nil {
		if x, ok := x.Hostname.(*ForwardRequestRequest_HostnameRaw); ok {
			return x.HostnameRaw
		}
	}
	return ""
}

func (x *ForwardRequestRequest) GetHostnameCode() int32 {
	if x != nil {
		if x, ok := x.Hostname.(*ForwardRequestRequest_HostnameCode); ok {
			return x.HostnameCode
		}
	}
	return 0
}

func (x *ForwardRequestRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type isForwardRequestRequest_ClientId interface {
	isForwardRequestRequest_ClientId()
}

type ForwardRequestRequest_ClientIp struct {
	ClientIp string `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3,oneof"` // 客户端 IP（首次使用）
}

type ForwardRequestRequest_ClientCode struct {
	ClientCode int32 `protobuf:"varint,2,opt,name=client_code,json=clientCode,proto3,oneof"` // 客户端编码（后续使用，节省流量）
}

func (*ForwardRequestRequest_ClientIp) isForwardRequestRequest_ClientId() {}

func (*ForwardRequestRequest_ClientCode) isForwardRequestRequest_ClientId() {}

type isForwardRequestRequest_Hostname interface {
	isForwardRequestRequest_Hostname()
}

type ForwardRequestRequest_HostnameRaw struct {
	HostnameRaw string `protobuf:"bytes,3,opt,name=hostname_raw,json=hostnameRaw,proto3,oneof"` // 原始主机名（首次使用）
}

type ForwardRequestRequest_HostnameCode struct {
	HostnameCode int32 `protobuf:"varint,4,opt,name=hostname_code,json=hostnameCode,proto3,oneof"` // 主机名编码（后续使用，节省流量）
}

func (*ForwardRequestRequest_HostnameRaw) isForwardRequestRequest_Hostname() {}

func (*ForwardRequestRequest_HostnameCode) isForwardRequestRequest_Hostname() {}

// 转发响应
type ForwardRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCode    int32                  `protobuf:"varint,1,opt,name=client_code,json=clientCode,proto3" json:"client_code,omitempty"`       // 客户端编码（回显）
	HostnameCode  int32                  `protobuf:"varint,2,opt,name=hostname_code,json=hostnameCode,proto3" json:"hostname_code,omitempty"` // 主机名编码（回显）
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`                                      // 路径（回显）
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                      // 响应体（仅状态码 200 时返回，其他状态码为空）
	StatusCode    int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`       // HTTP 状态码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequestResponse) Reset() {
	*x = ForwardRequestResponse{}
	mi := &file_httpforward_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequestResponse) ProtoMessage() {}

func (x *ForwardRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_httpforward_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequestResponse.ProtoReflect.Descriptor instead.
func (*ForwardRequestResponse) Descriptor() ([]byte, []int) {
	return file_httpforward_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardRequestResponse) GetClientCode() int32 {
	if x != nil {
		return x.ClientCode
	}
	return 0
}

func (x *ForwardRequestResponse) GetHostnameCode() int32 {
	if x != nil {
		return x.HostnameCode
	}
	return 0
}

func (x *ForwardRequestResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ForwardRequestResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ForwardRequestResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_httpforward_proto protoreflect.FileDescriptor

const file_httpforward_proto_rawDesc = "" +
	"\n" +
	"\x11httpforward.proto\x12\vhttpforward\"/\n" +
	"\x10HandshakeRequest\x12\x1b\n" +
	"\tclient_ip\x18\x01 \x01(\tR\bclientIp\"4\n" +
	"\x11HandshakeResponse\x12\x1f\n" +
	"\vclient_code\x18\x01 \x01(\x05R\n" +
	"clientCode\"\xd2\x01\n" +
	"\x15ForwardRequestRequest\x12\x1d\n" +
	"\tclient_ip\x18\x01 \x01(\tH\x00R\bclientIp\x12!\n" +
	"\vclient_code\x18\x02 \x01(\x05H\x00R\n" +
	"clientCode\x12#\n" +
	"\fhostname_raw\x18\x03 \x01(\tH\x01R\vhostnameRaw\x12%\n" +
	"\rhostname_code\x18\x04 \x01(\x05H\x01R\fhostnameCode\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04pathB\v\n" +
	"\tclient_idB\n" +
	"\n" +
	"\bhostname\"\xa7\x01\n" +
	"\x16ForwardRequestResponse\x12\x1f\n" +
	"\vclient_code\x18\x01 \x01(\x05R\n" +
	"clientCode\x12#\n" +
	"\rhostname_code\x18\x02 \x01(\x05R\fhostnameCode\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode2\xbb\x01\n" +
	"\x12HTTPForwardService\x12J\n" +
	"\tHandshake\x12\x1d.httpforward.HandshakeRequest\x1a\x1e.httpforward.HandshakeResponse\x12Y\n" +
	"\x0eForwardRequest\x12\".httpforward.ForwardRequestRequest\x1a#.httpforward.ForwardRequestResponseB\x1fZ\x1dutls_client/proto/httpforwardb\x06proto3"

var (
	file_httpforward_proto_rawDescOnce sync.Once
	file_httpforward_proto_rawDescData []byte
)

func file_httpforward_proto_rawDescGZIP() []byte {
	file_httpforward_proto_rawDescOnce.Do(func() {
		file_httpforward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_httpforward_proto_rawDesc), len(file_httpforward_proto_rawDesc)))
	})
	return file_httpforward_proto_rawDescData
}

var file_httpforward_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_httpforward_proto_goTypes = []any{
	(*HandshakeRequest)(nil),       // 0: httpforward.HandshakeRequest
	(*HandshakeResponse)(nil),      // 1: httpforward.HandshakeResponse
	(*ForwardRequestRequest)(nil),  // 2: httpforward.ForwardRequestRequest
	(*ForwardRequestResponse)(nil), // 3: httpforward.ForwardRequestResponse
}
var file_httpforward_proto_depIdxs = []int32{
	0, // 0: httpforward.HTTPForwardService.Handshake:input_type -> httpforward.HandshakeRequest
	2, // 1: httpforward.HTTPForwardService.ForwardRequest:input_type -> httpforward.ForwardRequestRequest
	1, // 2: httpforward.HTTPForwardService.Handshake:output_type -> httpforward.HandshakeResponse
	3, // 3: httpforward.HTTPForwardService.ForwardRequest:output_type -> httpforward.ForwardRequestResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_httpforward_proto_init() }
func file_httpforward_proto_init() {
	if File_httpforward_proto != nil {
		return
	}
	file_httpforward_proto_msgTypes[2].OneofWrappers = []any{
		(*ForwardRequestRequest_ClientIp)(nil),
		(*ForwardRequestRequest_ClientCode)(nil),
		(*ForwardRequestRequest_HostnameRaw)(nil),
		(*ForwardRequestRequest_HostnameCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_httpforward_proto_rawDesc), len(file_httpforward_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_httpforward_proto_goTypes,
		DependencyIndexes: file_httpforward_proto_depIdxs,
		MessageInfos:      file_httpforward_proto_msgTypes,
	}.Build()
	File_httpforward_proto = out.File
	file_httpforward_proto_goTypes = nil
	file_httpforward_proto_depIdxs = nil
}
